<?php return [
    ['name' => 'Badakhshan', 'country_id' => 1],
    ['name' => 'Badgis', 'country_id' => 1],
    ['name' => 'Baglan', 'country_id' => 1],
    ['name' => 'Balkh', 'country_id' => 1],
    ['name' => 'Bamiyan', 'country_id' => 1],
    ['name' => 'Farah', 'country_id' => 1],
    ['name' => 'Faryab', 'country_id' => 1],
    ['name' => 'Gawr', 'country_id' => 1],
    ['name' => 'Gazni', 'country_id' => 1],
    ['name' => 'Herat', 'country_id' => 1],
    ['name' => 'Hilmand', 'country_id' => 1],
    ['name' => 'Jawzjan', 'country_id' => 1],
    ['name' => 'Kabul', 'country_id' => 1],
    ['name' => 'Kapisa', 'country_id' => 1],
    ['name' => 'Khawst', 'country_id' => 1],
    ['name' => 'Kunar', 'country_id' => 1],
    ['name' => 'Lagman', 'country_id' => 1],
    ['name' => 'Lawghar', 'country_id' => 1],
    ['name' => 'Nangarhar', 'country_id' => 1],
    ['name' => 'Nimruz', 'country_id' => 1],
    ['name' => 'Nuristan', 'country_id' => 1],
    ['name' => 'Paktika', 'country_id' => 1],
    ['name' => 'Paktiya', 'country_id' => 1],
    ['name' => 'Parwan', 'country_id' => 1],
    ['name' => 'Qandahar', 'country_id' => 1],
    ['name' => 'Qunduz', 'country_id' => 1],
    ['name' => 'Samangan', 'country_id' => 1],
    ['name' => 'Sar-e Pul', 'country_id' => 1],
    ['name' => 'Takhar', 'country_id' => 1],
    ['name' => 'Uruzgan', 'country_id' => 1],
    ['name' => 'Wardak', 'country_id' => 1],
    ['name' => 'Zabul', 'country_id' => 1],
];