<?php return [
    ['name' => 'Buenos Aires', 'country_id' => 10],
    ['name' => 'Catamarca', 'country_id' => 10],
    ['name' => 'Chaco', 'country_id' => 10],
    ['name' => 'Chubut', 'country_id' => 10],
    ['name' => 'Cordoba', 'country_id' => 10],
    ['name' => 'Corrientes', 'country_id' => 10],
    ['name' => 'Distrito Federal', 'country_id' => 10],
    ['name' => 'Entre Rios', 'country_id' => 10],
    ['name' => 'Formosa', 'country_id' => 10],
    ['name' => 'Jujuy', 'country_id' => 10],
    ['name' => 'La Pampa', 'country_id' => 10],
    ['name' => 'La Rioja', 'country_id' => 10],
    ['name' => 'Mendoza', 'country_id' => 10],
    ['name' => 'Misiones', 'country_id' => 10],
    ['name' => 'Neuquen', 'country_id' => 10],
    ['name' => 'Rio Negro', 'country_id' => 10],
    ['name' => 'Salta', 'country_id' => 10],
    ['name' => 'San Juan', 'country_id' => 10],
    ['name' => 'San Luis', 'country_id' => 10],
    ['name' => 'Santa Cruz', 'country_id' => 10],
    ['name' => 'Santa Fe', 'country_id' => 10],
    ['name' => 'Santiago del Estero', 'country_id' => 10],
    ['name' => 'Tierra del Fuego', 'country_id' => 10],
    ['name' => 'Tucuman', 'country_id' => 10],
];