<?php return [
    ['name' => 'Aceh', 'country_id' => 102],
    ['name' => 'Bali', 'country_id' => 102],
    ['name' => 'Bangka-Belitung', 'country_id' => 102],
    ['name' => 'Banten', 'country_id' => 102],
    ['name' => 'Bengkulu', 'country_id' => 102],
    ['name' => 'Gandaria', 'country_id' => 102],
    ['name' => 'Gorontalo', 'country_id' => 102],
    ['name' => 'Jakarta', 'country_id' => 102],
    ['name' => 'Jambi', 'country_id' => 102],
    ['name' => 'Jawa Barat', 'country_id' => 102],
    ['name' => 'Jawa Tengah', 'country_id' => 102],
    ['name' => 'Jawa Timur', 'country_id' => 102],
    ['name' => 'Kalimantan Barat', 'country_id' => 102],
    ['name' => 'Kalimantan Selatan', 'country_id' => 102],
    ['name' => 'Kalimantan Tengah', 'country_id' => 102],
    ['name' => 'Kalimantan Timur', 'country_id' => 102],
    ['name' => 'Kendal', 'country_id' => 102],
    ['name' => 'Lampung', 'country_id' => 102],
    ['name' => 'Maluku', 'country_id' => 102],
    ['name' => 'Maluku Utara', 'country_id' => 102],
    ['name' => 'Nusa Tenggara Barat', 'country_id' => 102],
    ['name' => 'Nusa Tenggara Timur', 'country_id' => 102],
    ['name' => 'Papua', 'country_id' => 102],
    ['name' => 'Riau', 'country_id' => 102],
    ['name' => 'Riau Kepulauan', 'country_id' => 102],
    ['name' => 'Solo', 'country_id' => 102],
    ['name' => 'Sulawesi Selatan', 'country_id' => 102],
    ['name' => 'Sulawesi Tengah', 'country_id' => 102],
    ['name' => 'Sulawesi Tenggara', 'country_id' => 102],
    ['name' => 'Sulawesi Utara', 'country_id' => 102],
    ['name' => 'Sumatera Barat', 'country_id' => 102],
    ['name' => 'Sumatera Selatan', 'country_id' => 102],
    ['name' => 'Sumatera Utara', 'country_id' => 102],
    ['name' => 'Yogyakarta', 'country_id' => 102],
];