<?php return [
    ['name' => 'Ardabil', 'country_id' => 103],
    ['name' => 'Azarbayjan-e Bakhtari', 'country_id' => 103],
    ['name' => 'Azarbayjan-e Khavari', 'country_id' => 103],
    ['name' => 'Bushehr', 'country_id' => 103],
    ['name' => 'Chahar Mahal-e Bakhtiari', 'country_id' => 103],
    ['name' => 'Esfahan', 'country_id' => 103],
    ['name' => 'Fars', 'country_id' => 103],
    ['name' => 'Gilan', 'country_id' => 103],
    ['name' => 'Golestan', 'country_id' => 103],
    ['name' => 'Hamadan', 'country_id' => 103],
    ['name' => 'Hormozgan', 'country_id' => 103],
    ['name' => 'Ilam', 'country_id' => 103],
    ['name' => 'Kerman', 'country_id' => 103],
    ['name' => 'Kermanshah', 'country_id' => 103],
    ['name' => 'Khorasan', 'country_id' => 103],
    ['name' => 'Khuzestan', 'country_id' => 103],
    ['name' => 'Kohgiluyeh-e Boyerahmad', 'country_id' => 103],
    ['name' => 'Kordestan', 'country_id' => 103],
    ['name' => 'Lorestan', 'country_id' => 103],
    ['name' => 'Markazi', 'country_id' => 103],
    ['name' => 'Mazandaran', 'country_id' => 103],
    ['name' => 'Ostan-e Esfahan', 'country_id' => 103],
    ['name' => 'Qazvin', 'country_id' => 103],
    ['name' => 'Qom', 'country_id' => 103],
    ['name' => 'Semnan', 'country_id' => 103],
    ['name' => 'Sistan-e Baluchestan', 'country_id' => 103],
    ['name' => 'Tehran', 'country_id' => 103],
    ['name' => 'Yazd', 'country_id' => 103],
    ['name' => 'Zanjan', 'country_id' => 103],
];