<?php return [
    ['name' => 'Babil', 'country_id' => 104],
    ['name' => 'Baghdad', 'country_id' => 104],
    ['name' => 'Dahuk', 'country_id' => 104],
    ['name' => 'Dhi Qar', 'country_id' => 104],
    ['name' => 'Diyala', 'country_id' => 104],
    ['name' => 'Erbil', 'country_id' => 104],
    ['name' => 'Irbil', 'country_id' => 104],
    ['name' => 'Karbala', 'country_id' => 104],
    ['name' => 'Kurdistan', 'country_id' => 104],
    ['name' => 'Maysan', 'country_id' => 104],
    ['name' => 'Ninawa', 'country_id' => 104],
    ['name' => 'Salah-ad-Din', 'country_id' => 104],
    ['name' => 'Wasit', 'country_id' => 104],
    ['name' => 'al-Anbar', 'country_id' => 104],
    ['name' => 'al-Basrah', 'country_id' => 104],
    ['name' => 'al-Muthanna', 'country_id' => 104],
    ['name' => 'al-Qadisiyah', 'country_id' => 104],
    ['name' => 'an-Najaf', 'country_id' => 104],
    ['name' => 'as-Sulaymaniyah', 'country_id' => 104],
    ['name' => 'at-Ta\'mim', 'country_id' => 104],
];