<?php return [
    ['name' => 'Armagh', 'country_id' => 105],
    ['name' => 'Carlow', 'country_id' => 105],
    ['name' => 'Cavan', 'country_id' => 105],
    ['name' => 'Clare', 'country_id' => 105],
    ['name' => 'Cork', 'country_id' => 105],
    ['name' => 'Donegal', 'country_id' => 105],
    ['name' => 'Dublin', 'country_id' => 105],
    ['name' => 'Galway', 'country_id' => 105],
    ['name' => 'Kerry', 'country_id' => 105],
    ['name' => 'Kildare', 'country_id' => 105],
    ['name' => 'Kilkenny', 'country_id' => 105],
    ['name' => 'Laois', 'country_id' => 105],
    ['name' => 'Leinster', 'country_id' => 105],
    ['name' => 'Leitrim', 'country_id' => 105],
    ['name' => 'Limerick', 'country_id' => 105],
    ['name' => 'Loch Garman', 'country_id' => 105],
    ['name' => 'Longford', 'country_id' => 105],
    ['name' => 'Louth', 'country_id' => 105],
    ['name' => 'Mayo', 'country_id' => 105],
    ['name' => 'Meath', 'country_id' => 105],
    ['name' => 'Monaghan', 'country_id' => 105],
    ['name' => 'Offaly', 'country_id' => 105],
    ['name' => 'Roscommon', 'country_id' => 105],
    ['name' => 'Sligo', 'country_id' => 105],
    ['name' => 'Tipperary North Riding', 'country_id' => 105],
    ['name' => 'Tipperary South Riding', 'country_id' => 105],
    ['name' => 'Ulster', 'country_id' => 105],
    ['name' => 'Waterford', 'country_id' => 105],
    ['name' => 'Westmeath', 'country_id' => 105],
    ['name' => 'Wexford', 'country_id' => 105],
    ['name' => 'Wicklow', 'country_id' => 105],
];