<?php return [
    ['name' => 'Beit Hanania', 'country_id' => 106],
    ['name' => 'Ben Gurion Airport', 'country_id' => 106],
    ['name' => 'Bethlehem', 'country_id' => 106],
    ['name' => 'Caesarea', 'country_id' => 106],
    ['name' => 'Centre', 'country_id' => 106],
    ['name' => 'Gaza', 'country_id' => 106],
    ['name' => 'Hadaron', 'country_id' => 106],
    ['name' => 'Haifa District', 'country_id' => 106],
    ['name' => 'Hamerkaz', 'country_id' => 106],
    ['name' => 'Hazafon', 'country_id' => 106],
    ['name' => 'Hebron', 'country_id' => 106],
    ['name' => 'Jaffa', 'country_id' => 106],
    ['name' => 'Jerusalem', 'country_id' => 106],
    ['name' => 'Khefa', 'country_id' => 106],
    ['name' => 'Kiryat Yam', 'country_id' => 106],
    ['name' => 'Lower Galilee', 'country_id' => 106],
    ['name' => 'Qalqilya', 'country_id' => 106],
    ['name' => 'Talme Elazar', 'country_id' => 106],
    ['name' => 'Tel Aviv', 'country_id' => 106],
    ['name' => 'Tsafon', 'country_id' => 106],
    ['name' => 'Umm El Fahem', 'country_id' => 106],
    ['name' => 'Yerushalayim', 'country_id' => 106],
];