<?php return [
    ['name' => 'Abruzzi', 'country_id' => 107],
    ['name' => 'Abruzzo', 'country_id' => 107],
    ['name' => 'Agrigento', 'country_id' => 107],
    ['name' => 'Alessandria', 'country_id' => 107],
    ['name' => 'Ancona', 'country_id' => 107],
    ['name' => 'Arezzo', 'country_id' => 107],
    ['name' => 'Ascoli Piceno', 'country_id' => 107],
    ['name' => 'Asti', 'country_id' => 107],
    ['name' => 'Avellino', 'country_id' => 107],
    ['name' => 'Bari', 'country_id' => 107],
    ['name' => 'Basilicata', 'country_id' => 107],
    ['name' => 'Belluno', 'country_id' => 107],
    ['name' => 'Benevento', 'country_id' => 107],
    ['name' => 'Bergamo', 'country_id' => 107],
    ['name' => 'Biella', 'country_id' => 107],
    ['name' => 'Bologna', 'country_id' => 107],
    ['name' => 'Bolzano', 'country_id' => 107],
    ['name' => 'Brescia', 'country_id' => 107],
    ['name' => 'Brindisi', 'country_id' => 107],
    ['name' => 'Calabria', 'country_id' => 107],
    ['name' => 'Campania', 'country_id' => 107],
    ['name' => 'Cartoceto', 'country_id' => 107],
    ['name' => 'Caserta', 'country_id' => 107],
    ['name' => 'Catania', 'country_id' => 107],
    ['name' => 'Chieti', 'country_id' => 107],
    ['name' => 'Como', 'country_id' => 107],
    ['name' => 'Cosenza', 'country_id' => 107],
    ['name' => 'Cremona', 'country_id' => 107],
    ['name' => 'Cuneo', 'country_id' => 107],
    ['name' => 'Emilia-Romagna', 'country_id' => 107],
    ['name' => 'Ferrara', 'country_id' => 107],
    ['name' => 'Firenze', 'country_id' => 107],
    ['name' => 'Florence', 'country_id' => 107],
    ['name' => 'Forli-Cesena ', 'country_id' => 107],
    ['name' => 'Friuli-Venezia Giulia', 'country_id' => 107],
    ['name' => 'Frosinone', 'country_id' => 107],
    ['name' => 'Genoa', 'country_id' => 107],
    ['name' => 'Gorizia', 'country_id' => 107],
    ['name' => 'L\'Aquila', 'country_id' => 107],
    ['name' => 'Lazio', 'country_id' => 107],
    ['name' => 'Lecce', 'country_id' => 107],
    ['name' => 'Lecco', 'country_id' => 107],
    ['name' => 'Lecco Province', 'country_id' => 107],
    ['name' => 'Liguria', 'country_id' => 107],
    ['name' => 'Lodi', 'country_id' => 107],
    ['name' => 'Lombardia', 'country_id' => 107],
    ['name' => 'Lombardy', 'country_id' => 107],
    ['name' => 'Macerata', 'country_id' => 107],
    ['name' => 'Mantova', 'country_id' => 107],
    ['name' => 'Marche', 'country_id' => 107],
    ['name' => 'Messina', 'country_id' => 107],
    ['name' => 'Milan', 'country_id' => 107],
    ['name' => 'Modena', 'country_id' => 107],
    ['name' => 'Molise', 'country_id' => 107],
    ['name' => 'Molteno', 'country_id' => 107],
    ['name' => 'Montenegro', 'country_id' => 107],
    ['name' => 'Monza and Brianza', 'country_id' => 107],
    ['name' => 'Naples', 'country_id' => 107],
    ['name' => 'Novara', 'country_id' => 107],
    ['name' => 'Padova', 'country_id' => 107],
    ['name' => 'Parma', 'country_id' => 107],
    ['name' => 'Pavia', 'country_id' => 107],
    ['name' => 'Perugia', 'country_id' => 107],
    ['name' => 'Pesaro-Urbino', 'country_id' => 107],
    ['name' => 'Piacenza', 'country_id' => 107],
    ['name' => 'Piedmont', 'country_id' => 107],
    ['name' => 'Piemonte', 'country_id' => 107],
    ['name' => 'Pisa', 'country_id' => 107],
    ['name' => 'Pordenone', 'country_id' => 107],
    ['name' => 'Potenza', 'country_id' => 107],
    ['name' => 'Puglia', 'country_id' => 107],
    ['name' => 'Reggio Emilia', 'country_id' => 107],
    ['name' => 'Rimini', 'country_id' => 107],
    ['name' => 'Roma', 'country_id' => 107],
    ['name' => 'Salerno', 'country_id' => 107],
    ['name' => 'Sardegna', 'country_id' => 107],
    ['name' => 'Sassari', 'country_id' => 107],
    ['name' => 'Savona', 'country_id' => 107],
    ['name' => 'Sicilia', 'country_id' => 107],
    ['name' => 'Siena', 'country_id' => 107],
    ['name' => 'Sondrio', 'country_id' => 107],
    ['name' => 'South Tyrol', 'country_id' => 107],
    ['name' => 'Taranto', 'country_id' => 107],
    ['name' => 'Teramo', 'country_id' => 107],
    ['name' => 'Torino', 'country_id' => 107],
    ['name' => 'Toscana', 'country_id' => 107],
    ['name' => 'Trapani', 'country_id' => 107],
    ['name' => 'Trentino-Alto Adige', 'country_id' => 107],
    ['name' => 'Trento', 'country_id' => 107],
    ['name' => 'Treviso', 'country_id' => 107],
    ['name' => 'Udine', 'country_id' => 107],
    ['name' => 'Umbria', 'country_id' => 107],
    ['name' => 'Valle d\'Aosta', 'country_id' => 107],
    ['name' => 'Varese', 'country_id' => 107],
    ['name' => 'Veneto', 'country_id' => 107],
    ['name' => 'Venezia', 'country_id' => 107],
    ['name' => 'Verbano-Cusio-Ossola', 'country_id' => 107],
    ['name' => 'Vercelli', 'country_id' => 107],
    ['name' => 'Verona', 'country_id' => 107],
    ['name' => 'Vicenza', 'country_id' => 107],
    ['name' => 'Viterbo', 'country_id' => 107],
];