<?php return [
    ['name' => 'Abaiang', 'country_id' => 114],
    ['name' => 'Abemana', 'country_id' => 114],
    ['name' => 'Aranuka', 'country_id' => 114],
    ['name' => 'Arorae', 'country_id' => 114],
    ['name' => 'Banaba', 'country_id' => 114],
    ['name' => 'Beru', 'country_id' => 114],
    ['name' => 'Butaritari', 'country_id' => 114],
    ['name' => 'Kiritimati', 'country_id' => 114],
    ['name' => 'Kuria', 'country_id' => 114],
    ['name' => 'Maiana', 'country_id' => 114],
    ['name' => 'Makin', 'country_id' => 114],
    ['name' => 'Marakei', 'country_id' => 114],
    ['name' => 'Nikunau', 'country_id' => 114],
    ['name' => 'Nonouti', 'country_id' => 114],
    ['name' => 'Onotoa', 'country_id' => 114],
    ['name' => 'Phoenix Islands', 'country_id' => 114],
    ['name' => 'Tabiteuea North', 'country_id' => 114],
    ['name' => 'Tabiteuea South', 'country_id' => 114],
    ['name' => 'Tabuaeran', 'country_id' => 114],
    ['name' => 'Tamana', 'country_id' => 114],
    ['name' => 'Tarawa North', 'country_id' => 114],
    ['name' => 'Tarawa South', 'country_id' => 114],
    ['name' => 'Teraina', 'country_id' => 114],
];