<?php return [
    ['name' => 'Busan', 'country_id' => 116],
    ['name' => 'Cheju', 'country_id' => 116],
    ['name' => 'Chollabuk', 'country_id' => 116],
    ['name' => 'Chollanam', 'country_id' => 116],
    ['name' => 'Chungbuk', 'country_id' => 116],
    ['name' => 'Chungcheongbuk', 'country_id' => 116],
    ['name' => 'Chungcheongnam', 'country_id' => 116],
    ['name' => 'Chungnam', 'country_id' => 116],
    ['name' => 'Daegu', 'country_id' => 116],
    ['name' => 'Gangwon-do', 'country_id' => 116],
    ['name' => 'Goyang-si', 'country_id' => 116],
    ['name' => 'Gyeonggi-do', 'country_id' => 116],
    ['name' => 'Gyeongsang ', 'country_id' => 116],
    ['name' => 'Gyeongsangnam-do', 'country_id' => 116],
    ['name' => 'Incheon', 'country_id' => 116],
    ['name' => 'Jeju-Si', 'country_id' => 116],
    ['name' => 'Jeonbuk', 'country_id' => 116],
    ['name' => 'Kangweon', 'country_id' => 116],
    ['name' => 'Kwangju', 'country_id' => 116],
    ['name' => 'Kyeonggi', 'country_id' => 116],
    ['name' => 'Kyeongsangbuk', 'country_id' => 116],
    ['name' => 'Kyeongsangnam', 'country_id' => 116],
    ['name' => 'Kyonggi-do', 'country_id' => 116],
    ['name' => 'Kyungbuk-Do', 'country_id' => 116],
    ['name' => 'Kyunggi-Do', 'country_id' => 116],
    ['name' => 'Kyunggi-do', 'country_id' => 116],
    ['name' => 'Pusan', 'country_id' => 116],
    ['name' => 'Seoul', 'country_id' => 116],
    ['name' => 'Sudogwon', 'country_id' => 116],
    ['name' => 'Taegu', 'country_id' => 116],
    ['name' => 'Taejeon', 'country_id' => 116],
    ['name' => 'Taejon-gwangyoksi', 'country_id' => 116],
    ['name' => 'Ulsan', 'country_id' => 116],
    ['name' => 'Wonju', 'country_id' => 116],
    ['name' => 'gwangyoksi', 'country_id' => 116],
];