<?php return [
    ['name' => 'Attopu', 'country_id' => 119],
    ['name' => 'Bokeo', 'country_id' => 119],
    ['name' => 'Bolikhamsay', 'country_id' => 119],
    ['name' => 'Champasak', 'country_id' => 119],
    ['name' => 'Houaphanh', 'country_id' => 119],
    ['name' => 'Khammouane', 'country_id' => 119],
    ['name' => 'Luang Nam Tha', 'country_id' => 119],
    ['name' => 'Luang Prabang', 'country_id' => 119],
    ['name' => 'Oudomxay', 'country_id' => 119],
    ['name' => 'Phongsaly', 'country_id' => 119],
    ['name' => 'Saravan', 'country_id' => 119],
    ['name' => 'Savannakhet', 'country_id' => 119],
    ['name' => 'Sekong', 'country_id' => 119],
    ['name' => 'Viangchan Prefecture', 'country_id' => 119],
    ['name' => 'Viangchan Province', 'country_id' => 119],
    ['name' => 'Xaignabury', 'country_id' => 119],
    ['name' => 'Xiang Khuang', 'country_id' => 119],
];