<?php return [
    ['name' => 'Aizkraukles', 'country_id' => 120],
    ['name' => 'Aluksnes', 'country_id' => 120],
    ['name' => 'Balvu', 'country_id' => 120],
    ['name' => 'Bauskas', 'country_id' => 120],
    ['name' => 'Cesu', 'country_id' => 120],
    ['name' => 'Daugavpils', 'country_id' => 120],
    ['name' => 'Daugavpils City', 'country_id' => 120],
    ['name' => 'Dobeles', 'country_id' => 120],
    ['name' => 'Gulbenes', 'country_id' => 120],
    ['name' => 'Jekabspils', 'country_id' => 120],
    ['name' => 'Jelgava', 'country_id' => 120],
    ['name' => 'Jelgavas', 'country_id' => 120],
    ['name' => 'Jurmala City', 'country_id' => 120],
    ['name' => 'Kraslavas', 'country_id' => 120],
    ['name' => 'Kuldigas', 'country_id' => 120],
    ['name' => 'Liepaja', 'country_id' => 120],
    ['name' => 'Liepajas', 'country_id' => 120],
    ['name' => 'Limbazhu', 'country_id' => 120],
    ['name' => 'Ludzas', 'country_id' => 120],
    ['name' => 'Madonas', 'country_id' => 120],
    ['name' => 'Ogres', 'country_id' => 120],
    ['name' => 'Preilu', 'country_id' => 120],
    ['name' => 'Rezekne', 'country_id' => 120],
    ['name' => 'Rezeknes', 'country_id' => 120],
    ['name' => 'Riga', 'country_id' => 120],
    ['name' => 'Rigas', 'country_id' => 120],
    ['name' => 'Saldus', 'country_id' => 120],
    ['name' => 'Talsu', 'country_id' => 120],
    ['name' => 'Tukuma', 'country_id' => 120],
    ['name' => 'Valkas', 'country_id' => 120],
    ['name' => 'Valmieras', 'country_id' => 120],
    ['name' => 'Ventspils', 'country_id' => 120],
    ['name' => 'Ventspils City', 'country_id' => 120],
];