<?php return [
    ['name' => 'Ajdabiya', 'country_id' => 124],
    ['name' => 'Fezzan', 'country_id' => 124],
    ['name' => 'Banghazi', 'country_id' => 124],
    ['name' => 'Darnah', 'country_id' => 124],
    ['name' => 'Ghadamis', 'country_id' => 124],
    ['name' => 'Gharyan', 'country_id' => 124],
    ['name' => 'Misratah', 'country_id' => 124],
    ['name' => 'Murzuq', 'country_id' => 124],
    ['name' => 'Sabha', 'country_id' => 124],
    ['name' => 'Sawfajjin', 'country_id' => 124],
    ['name' => 'Surt', 'country_id' => 124],
    ['name' => 'Tarabulus', 'country_id' => 124],
    ['name' => 'Tarhunah', 'country_id' => 124],
    ['name' => 'Tripolitania', 'country_id' => 124],
    ['name' => 'Tubruq', 'country_id' => 124],
    ['name' => 'Yafran', 'country_id' => 124],
    ['name' => 'Zlitan', 'country_id' => 124],
    ['name' => 'al-\'Aziziyah', 'country_id' => 124],
    ['name' => 'al-Fatih', 'country_id' => 124],
    ['name' => 'al-Jabal al Akhdar', 'country_id' => 124],
    ['name' => 'al-Jufrah', 'country_id' => 124],
    ['name' => 'al-Khums', 'country_id' => 124],
    ['name' => 'al-Kufrah', 'country_id' => 124],
    ['name' => 'an-Nuqat al-Khams', 'country_id' => 124],
    ['name' => 'ash-Shati\'', 'country_id' => 124],
    ['name' => 'az-Zawiyah', 'country_id' => 124],
];