<?php return [
    ['name' => 'Berovo', 'country_id' => 129],
    ['name' => 'Bitola', 'country_id' => 129],
    ['name' => 'Brod', 'country_id' => 129],
    ['name' => 'Debar', 'country_id' => 129],
    ['name' => 'Delchevo', 'country_id' => 129],
    ['name' => 'Demir Hisar', 'country_id' => 129],
    ['name' => 'Gevgelija', 'country_id' => 129],
    ['name' => 'Gostivar', 'country_id' => 129],
    ['name' => 'Kavadarci', 'country_id' => 129],
    ['name' => 'Kichevo', 'country_id' => 129],
    ['name' => 'Kochani', 'country_id' => 129],
    ['name' => 'Kratovo', 'country_id' => 129],
    ['name' => 'Kriva Palanka', 'country_id' => 129],
    ['name' => 'Krushevo', 'country_id' => 129],
    ['name' => 'Kumanovo', 'country_id' => 129],
    ['name' => 'Negotino', 'country_id' => 129],
    ['name' => 'Ohrid', 'country_id' => 129],
    ['name' => 'Prilep', 'country_id' => 129],
    ['name' => 'Probishtip', 'country_id' => 129],
    ['name' => 'Radovish', 'country_id' => 129],
    ['name' => 'Resen', 'country_id' => 129],
    ['name' => 'Shtip', 'country_id' => 129],
    ['name' => 'Skopje', 'country_id' => 129],
    ['name' => 'Struga', 'country_id' => 129],
    ['name' => 'Strumica', 'country_id' => 129],
    ['name' => 'Sveti Nikole', 'country_id' => 129],
    ['name' => 'Tetovo', 'country_id' => 129],
    ['name' => 'Valandovo', 'country_id' => 129],
    ['name' => 'Veles', 'country_id' => 129],
    ['name' => 'Vinica', 'country_id' => 129],
];