<?php return [
    ['name' => 'Auckland', 'country_id' => 13],
    ['name' => 'Australian Capital Territory', 'country_id' => 13],
    ['name' => 'Balgowlah', 'country_id' => 13],
    ['name' => 'Balmain', 'country_id' => 13],
    ['name' => 'Bankstown', 'country_id' => 13],
    ['name' => 'Baulkham Hills', 'country_id' => 13],
    ['name' => 'Bonnet Bay', 'country_id' => 13],
    ['name' => 'Camberwell', 'country_id' => 13],
    ['name' => 'Carole Park', 'country_id' => 13],
    ['name' => 'Castle Hill', 'country_id' => 13],
    ['name' => 'Caulfield', 'country_id' => 13],
    ['name' => 'Chatswood', 'country_id' => 13],
    ['name' => 'Cheltenham', 'country_id' => 13],
    ['name' => 'Cherrybrook', 'country_id' => 13],
    ['name' => 'Clayton', 'country_id' => 13],
    ['name' => 'Collingwood', 'country_id' => 13],
    ['name' => 'Frenchs Forest', 'country_id' => 13],
    ['name' => 'Hawthorn', 'country_id' => 13],
    ['name' => 'Jannnali', 'country_id' => 13],
    ['name' => 'Knoxfield', 'country_id' => 13],
    ['name' => 'Melbourne', 'country_id' => 13],
    ['name' => 'New South Wales', 'country_id' => 13],
    ['name' => 'Northern Territory', 'country_id' => 13],
    ['name' => 'Perth', 'country_id' => 13],
    ['name' => 'Queensland', 'country_id' => 13],
    ['name' => 'South Australia', 'country_id' => 13],
    ['name' => 'Tasmania', 'country_id' => 13],
    ['name' => 'Templestowe', 'country_id' => 13],
    ['name' => 'Victoria', 'country_id' => 13],
    ['name' => 'Werribee south', 'country_id' => 13],
    ['name' => 'Western Australia', 'country_id' => 13],
    ['name' => 'Wheeler', 'country_id' => 13],
];