<?php return [
    ['name' => 'Balaka', 'country_id' => 131],
    ['name' => 'Blantyre City', 'country_id' => 131],
    ['name' => 'Chikwawa', 'country_id' => 131],
    ['name' => 'Chiradzulu', 'country_id' => 131],
    ['name' => 'Chitipa', 'country_id' => 131],
    ['name' => 'Dedza', 'country_id' => 131],
    ['name' => 'Dowa', 'country_id' => 131],
    ['name' => 'Karonga', 'country_id' => 131],
    ['name' => 'Kasungu', 'country_id' => 131],
    ['name' => 'Lilongwe City', 'country_id' => 131],
    ['name' => 'Machinga', 'country_id' => 131],
    ['name' => 'Mangochi', 'country_id' => 131],
    ['name' => 'Mchinji', 'country_id' => 131],
    ['name' => 'Mulanje', 'country_id' => 131],
    ['name' => 'Mwanza', 'country_id' => 131],
    ['name' => 'Mzimba', 'country_id' => 131],
    ['name' => 'Mzuzu City', 'country_id' => 131],
    ['name' => 'Nkhata Bay', 'country_id' => 131],
    ['name' => 'Nkhotakota', 'country_id' => 131],
    ['name' => 'Nsanje', 'country_id' => 131],
    ['name' => 'Ntcheu', 'country_id' => 131],
    ['name' => 'Ntchisi', 'country_id' => 131],
    ['name' => 'Phalombe', 'country_id' => 131],
    ['name' => 'Rumphi', 'country_id' => 131],
    ['name' => 'Salima', 'country_id' => 131],
    ['name' => 'Thyolo', 'country_id' => 131],
    ['name' => 'Zomba Municipality', 'country_id' => 131],
];