<?php return [
    ['name' => 'Johor', 'country_id' => 132],
    ['name' => 'Kedah', 'country_id' => 132],
    ['name' => 'Kelantan', 'country_id' => 132],
    ['name' => 'Kuala Lumpur', 'country_id' => 132],
    ['name' => 'Labuan', 'country_id' => 132],
    ['name' => 'Melaka', 'country_id' => 132],
    ['name' => 'Negeri Johor', 'country_id' => 132],
    ['name' => 'Negeri Sembilan', 'country_id' => 132],
    ['name' => 'Pahang', 'country_id' => 132],
    ['name' => 'Penang', 'country_id' => 132],
    ['name' => 'Perak', 'country_id' => 132],
    ['name' => 'Perlis', 'country_id' => 132],
    ['name' => 'Pulau Pinang', 'country_id' => 132],
    ['name' => 'Sabah', 'country_id' => 132],
    ['name' => 'Sarawak', 'country_id' => 132],
    ['name' => 'Selangor', 'country_id' => 132],
    ['name' => 'Sembilan', 'country_id' => 132],
    ['name' => 'Terengganu', 'country_id' => 132],
];