<?php return [
    ['name' => 'Alif Alif', 'country_id' => 133],
    ['name' => 'Alif Dhaal', 'country_id' => 133],
    ['name' => 'Baa', 'country_id' => 133],
    ['name' => 'Dhaal', 'country_id' => 133],
    ['name' => 'Faaf', 'country_id' => 133],
    ['name' => 'Gaaf Alif', 'country_id' => 133],
    ['name' => 'Gaaf Dhaal', 'country_id' => 133],
    ['name' => 'Ghaviyani', 'country_id' => 133],
    ['name' => 'Haa Alif', 'country_id' => 133],
    ['name' => 'Haa Dhaal', 'country_id' => 133],
    ['name' => 'Kaaf', 'country_id' => 133],
    ['name' => 'Laam', 'country_id' => 133],
    ['name' => 'Lhaviyani', 'country_id' => 133],
    ['name' => 'Male', 'country_id' => 133],
    ['name' => 'Miim', 'country_id' => 133],
    ['name' => 'Nuun', 'country_id' => 133],
    ['name' => 'Raa', 'country_id' => 133],
    ['name' => 'Shaviyani', 'country_id' => 133],
    ['name' => 'Siin', 'country_id' => 133],
    ['name' => 'Thaa', 'country_id' => 133],
    ['name' => 'Vaav', 'country_id' => 133],
];