<?php return [
    ['name' => 'Ailinlaplap', 'country_id' => 137],
    ['name' => 'Ailuk', 'country_id' => 137],
    ['name' => 'Arno', 'country_id' => 137],
    ['name' => 'Aur', 'country_id' => 137],
    ['name' => 'Bikini', 'country_id' => 137],
    ['name' => 'Ebon', 'country_id' => 137],
    ['name' => 'Enewetak', 'country_id' => 137],
    ['name' => 'Jabat', 'country_id' => 137],
    ['name' => 'Jaluit', 'country_id' => 137],
    ['name' => 'Kili', 'country_id' => 137],
    ['name' => 'Kwajalein', 'country_id' => 137],
    ['name' => 'Lae', 'country_id' => 137],
    ['name' => 'Lib', 'country_id' => 137],
    ['name' => 'Likiep', 'country_id' => 137],
    ['name' => 'Majuro', 'country_id' => 137],
    ['name' => 'Maloelap', 'country_id' => 137],
    ['name' => 'Mejit', 'country_id' => 137],
    ['name' => 'Mili', 'country_id' => 137],
    ['name' => 'Namorik', 'country_id' => 137],
    ['name' => 'Namu', 'country_id' => 137],
    ['name' => 'Rongelap', 'country_id' => 137],
    ['name' => 'Ujae', 'country_id' => 137],
    ['name' => 'Utrik', 'country_id' => 137],
    ['name' => 'Wotho', 'country_id' => 137],
    ['name' => 'Wotje', 'country_id' => 137],
];