<?php return [
    ['name' => 'Adrar', 'country_id' => 139],
    ['name' => 'Assaba', 'country_id' => 139],
    ['name' => 'Brakna', 'country_id' => 139],
    ['name' => 'Dhakhlat Nawadibu', 'country_id' => 139],
    ['name' => 'Hudh-al-Gharbi', 'country_id' => 139],
    ['name' => 'Hudh-ash-Sharqi', 'country_id' => 139],
    ['name' => 'Inshiri', 'country_id' => 139],
    ['name' => 'Nawakshut', 'country_id' => 139],
    ['name' => 'Qidimagha', 'country_id' => 139],
    ['name' => 'Qurqul', 'country_id' => 139],
    ['name' => 'Taqant', 'country_id' => 139],
    ['name' => 'Tiris Zammur', 'country_id' => 139],
    ['name' => 'Trarza', 'country_id' => 139],
];