<?php return [
    ['name' => 'Bundesland Salzburg', 'country_id' => 14],
    ['name' => 'Bundesland Steiermark', 'country_id' => 14],
    ['name' => 'Bundesland Tirol', 'country_id' => 14],
    ['name' => 'Burgenland', 'country_id' => 14],
    ['name' => 'Carinthia', 'country_id' => 14],
    ['name' => 'Karnten', 'country_id' => 14],
    ['name' => 'Liezen', 'country_id' => 14],
    ['name' => 'Lower Austria', 'country_id' => 14],
    ['name' => 'Niederosterreich', 'country_id' => 14],
    ['name' => 'Oberosterreich', 'country_id' => 14],
    ['name' => 'Salzburg', 'country_id' => 14],
    ['name' => 'Schleswig-Holstein', 'country_id' => 14],
    ['name' => 'Steiermark', 'country_id' => 14],
    ['name' => 'Styria', 'country_id' => 14],
    ['name' => 'Tirol', 'country_id' => 14],
    ['name' => 'Upper Austria', 'country_id' => 14],
    ['name' => 'Vorarlberg', 'country_id' => 14],
    ['name' => 'Wien', 'country_id' => 14],
];