<?php return [
    ['name' => 'Black River', 'country_id' => 140],
    ['name' => 'Eau Coulee', 'country_id' => 140],
    ['name' => 'Flacq', 'country_id' => 140],
    ['name' => 'Floreal', 'country_id' => 140],
    ['name' => 'Grand Port', 'country_id' => 140],
    ['name' => 'Moka', 'country_id' => 140],
    ['name' => 'Pamplempousses', 'country_id' => 140],
    ['name' => 'Plaines Wilhelm', 'country_id' => 140],
    ['name' => 'Port Louis', 'country_id' => 140],
    ['name' => 'Riviere du Rempart', 'country_id' => 140],
    ['name' => 'Rodrigues', 'country_id' => 140],
    ['name' => 'Rose Hill', 'country_id' => 140],
    ['name' => 'Savanne', 'country_id' => 140],
];