<?php return [
    ['name' => 'Aguascalientes', 'country_id' => 142],
    ['name' => 'Baja California', 'country_id' => 142],
    ['name' => 'Baja California Sur', 'country_id' => 142],
    ['name' => 'Campeche', 'country_id' => 142],
    ['name' => 'Chiapas', 'country_id' => 142],
    ['name' => 'Chihuahua', 'country_id' => 142],
    ['name' => 'Coahuila', 'country_id' => 142],
    ['name' => 'Colima', 'country_id' => 142],
    ['name' => 'Distrito Federal', 'country_id' => 142],
    ['name' => 'Durango', 'country_id' => 142],
    ['name' => 'Estado de Mexico', 'country_id' => 142],
    ['name' => 'Guanajuato', 'country_id' => 142],
    ['name' => 'Guerrero', 'country_id' => 142],
    ['name' => 'Hidalgo', 'country_id' => 142],
    ['name' => 'Jalisco', 'country_id' => 142],
    ['name' => 'Mexico', 'country_id' => 142],
    ['name' => 'Michoacan', 'country_id' => 142],
    ['name' => 'Morelos', 'country_id' => 142],
    ['name' => 'Nayarit', 'country_id' => 142],
    ['name' => 'Nuevo Leon', 'country_id' => 142],
    ['name' => 'Oaxaca', 'country_id' => 142],
    ['name' => 'Puebla', 'country_id' => 142],
    ['name' => 'Queretaro', 'country_id' => 142],
    ['name' => 'Quintana Roo', 'country_id' => 142],
    ['name' => 'San Luis Potosi', 'country_id' => 142],
    ['name' => 'Sinaloa', 'country_id' => 142],
    ['name' => 'Sonora', 'country_id' => 142],
    ['name' => 'Tabasco', 'country_id' => 142],
    ['name' => 'Tamaulipas', 'country_id' => 142],
    ['name' => 'Tlaxcala', 'country_id' => 142],
    ['name' => 'Veracruz', 'country_id' => 142],
    ['name' => 'Yucatan', 'country_id' => 142],
    ['name' => 'Zacatecas', 'country_id' => 142],
];