<?php return [
    ['name' => 'Arhangaj', 'country_id' => 146],
    ['name' => 'Bajan-Olgij', 'country_id' => 146],
    ['name' => 'Bajanhongor', 'country_id' => 146],
    ['name' => 'Bulgan', 'country_id' => 146],
    ['name' => 'Darhan-Uul', 'country_id' => 146],
    ['name' => 'Dornod', 'country_id' => 146],
    ['name' => 'Dornogovi', 'country_id' => 146],
    ['name' => 'Dundgovi', 'country_id' => 146],
    ['name' => 'Govi-Altaj', 'country_id' => 146],
    ['name' => 'Govisumber', 'country_id' => 146],
    ['name' => 'Hentij', 'country_id' => 146],
    ['name' => 'Hovd', 'country_id' => 146],
    ['name' => 'Hovsgol', 'country_id' => 146],
    ['name' => 'Omnogovi', 'country_id' => 146],
    ['name' => 'Orhon', 'country_id' => 146],
    ['name' => 'Ovorhangaj', 'country_id' => 146],
    ['name' => 'Selenge', 'country_id' => 146],
    ['name' => 'Suhbaatar', 'country_id' => 146],
    ['name' => 'Tov', 'country_id' => 146],
    ['name' => 'Ulaanbaatar', 'country_id' => 146],
    ['name' => 'Uvs', 'country_id' => 146],
    ['name' => 'Zavhan', 'country_id' => 146],
];