<?php return [
    ['name' => 'Agadir', 'country_id' => 148],
    ['name' => 'Casablanca', 'country_id' => 148],
    ['name' => 'Chaouia-Ouardigha', 'country_id' => 148],
    ['name' => 'Doukkala-Abda', 'country_id' => 148],
    ['name' => 'Fes-Boulemane', 'country_id' => 148],
    ['name' => 'Gharb-Chrarda-Beni Hssen', 'country_id' => 148],
    ['name' => 'Guelmim', 'country_id' => 148],
    ['name' => 'Kenitra', 'country_id' => 148],
    ['name' => 'Marrakech-Tensift-Al Haouz', 'country_id' => 148],
    ['name' => 'Meknes-Tafilalet', 'country_id' => 148],
    ['name' => 'Oriental', 'country_id' => 148],
    ['name' => 'Oujda', 'country_id' => 148],
    ['name' => 'Province de Tanger', 'country_id' => 148],
    ['name' => 'Rabat-Sale-Zammour-Zaer', 'country_id' => 148],
    ['name' => 'Sala Al Jadida', 'country_id' => 148],
    ['name' => 'Settat', 'country_id' => 148],
    ['name' => 'Souss Massa-Draa', 'country_id' => 148],
    ['name' => 'Tadla-Azilal', 'country_id' => 148],
    ['name' => 'Tangier-Tetouan', 'country_id' => 148],
    ['name' => 'Taza-Al Hoceima-Taounate', 'country_id' => 148],
    ['name' => 'Wilaya de Casablanca', 'country_id' => 148],
    ['name' => 'Wilaya de Rabat-Sale', 'country_id' => 148],
];