<?php return [
    ['name' => 'Ayeyarwady', 'country_id' => 150],
    ['name' => 'Bago', 'country_id' => 150],
    ['name' => 'Chin', 'country_id' => 150],
    ['name' => 'Kachin', 'country_id' => 150],
    ['name' => 'Kayah', 'country_id' => 150],
    ['name' => 'Kayin', 'country_id' => 150],
    ['name' => 'Magway', 'country_id' => 150],
    ['name' => 'Mandalay', 'country_id' => 150],
    ['name' => 'Mon', 'country_id' => 150],
    ['name' => 'Nay Pyi Taw', 'country_id' => 150],
    ['name' => 'Rakhine', 'country_id' => 150],
    ['name' => 'Sagaing', 'country_id' => 150],
    ['name' => 'Shan', 'country_id' => 150],
    ['name' => 'Tanintharyi', 'country_id' => 150],
    ['name' => 'Yangon', 'country_id' => 150],
];