<?php return [
    ['name' => 'Bagmati', 'country_id' => 153],
    ['name' => 'Bheri', 'country_id' => 153],
    ['name' => 'Dhawalagiri', 'country_id' => 153],
    ['name' => 'Gandaki', 'country_id' => 153],
    ['name' => 'Janakpur', 'country_id' => 153],
    ['name' => 'Karnali', 'country_id' => 153],
    ['name' => 'Koshi', 'country_id' => 153],
    ['name' => 'Lumbini', 'country_id' => 153],
    ['name' => 'Mahakali', 'country_id' => 153],
    ['name' => 'Mechi', 'country_id' => 153],
    ['name' => 'Narayani', 'country_id' => 153],
    ['name' => 'Rapti', 'country_id' => 153],
    ['name' => 'Sagarmatha', 'country_id' => 153],
    ['name' => 'Seti', 'country_id' => 153],
];