<?php return [
    ['name' => 'Amsterdam', 'country_id' => 155],
    ['name' => 'Benelux', 'country_id' => 155],
    ['name' => 'Drenthe', 'country_id' => 155],
    ['name' => 'Flevoland', 'country_id' => 155],
    ['name' => 'Friesland', 'country_id' => 155],
    ['name' => 'Gelderland', 'country_id' => 155],
    ['name' => 'Groningen', 'country_id' => 155],
    ['name' => 'Limburg', 'country_id' => 155],
    ['name' => 'Noord-Brabant', 'country_id' => 155],
    ['name' => 'Noord-Holland', 'country_id' => 155],
    ['name' => 'Overijssel', 'country_id' => 155],
    ['name' => 'South Holland', 'country_id' => 155],
    ['name' => 'Utrecht', 'country_id' => 155],
    ['name' => 'Zeeland', 'country_id' => 155],
    ['name' => 'Zuid-Holland', 'country_id' => 155],
];