<?php return [
    ['name' => 'Area Outside Region', 'country_id' => 157],
    ['name' => 'Auckland', 'country_id' => 157],
    ['name' => 'Bay of Plenty', 'country_id' => 157],
    ['name' => 'Canterbury', 'country_id' => 157],
    ['name' => 'Christchurch', 'country_id' => 157],
    ['name' => 'Gisborne', 'country_id' => 157],
    ['name' => 'Hawke\'s Bay', 'country_id' => 157],
    ['name' => 'Manawatu-Wanganui', 'country_id' => 157],
    ['name' => 'Marlborough', 'country_id' => 157],
    ['name' => 'Nelson', 'country_id' => 157],
    ['name' => 'Northland', 'country_id' => 157],
    ['name' => 'Otago', 'country_id' => 157],
    ['name' => 'Rodney', 'country_id' => 157],
    ['name' => 'Southland', 'country_id' => 157],
    ['name' => 'Taranaki', 'country_id' => 157],
    ['name' => 'Tasman', 'country_id' => 157],
    ['name' => 'Waikato', 'country_id' => 157],
    ['name' => 'Wellington', 'country_id' => 157],
    ['name' => 'West Coast', 'country_id' => 157],
];