<?php return [
    ['name' => 'Atlantico Norte', 'country_id' => 158],
    ['name' => 'Atlantico Sur', 'country_id' => 158],
    ['name' => 'Boaco', 'country_id' => 158],
    ['name' => 'Carazo', 'country_id' => 158],
    ['name' => 'Chinandega', 'country_id' => 158],
    ['name' => 'Chontales', 'country_id' => 158],
    ['name' => 'Esteli', 'country_id' => 158],
    ['name' => 'Granada', 'country_id' => 158],
    ['name' => 'Jinotega', 'country_id' => 158],
    ['name' => 'Leon', 'country_id' => 158],
    ['name' => 'Madriz', 'country_id' => 158],
    ['name' => 'Managua', 'country_id' => 158],
    ['name' => 'Masaya', 'country_id' => 158],
    ['name' => 'Matagalpa', 'country_id' => 158],
    ['name' => 'Nueva Segovia', 'country_id' => 158],
    ['name' => 'Rio San Juan', 'country_id' => 158],
    ['name' => 'Rivas', 'country_id' => 158],
];