<?php return [
    ['name' => 'Abaco', 'country_id' => 16],
    ['name' => 'Acklins Island', 'country_id' => 16],
    ['name' => 'Andros', 'country_id' => 16],
    ['name' => 'Berry Islands', 'country_id' => 16],
    ['name' => 'Biminis', 'country_id' => 16],
    ['name' => 'Cat Island', 'country_id' => 16],
    ['name' => 'Crooked Island', 'country_id' => 16],
    ['name' => 'Eleuthera', 'country_id' => 16],
    ['name' => 'Exuma and Cays', 'country_id' => 16],
    ['name' => 'Grand Bahama', 'country_id' => 16],
    ['name' => 'Inagua Islands', 'country_id' => 16],
    ['name' => 'Long Island', 'country_id' => 16],
    ['name' => 'Mayaguana', 'country_id' => 16],
    ['name' => 'New Providence', 'country_id' => 16],
    ['name' => 'Ragged Island', 'country_id' => 16],
    ['name' => 'Rum Cay', 'country_id' => 16],
    ['name' => 'San Salvador', 'country_id' => 16],
];