<?php return [
    ['name' => 'Akershus', 'country_id' => 164],
    ['name' => 'Aust Agder', 'country_id' => 164],
    ['name' => 'Bergen', 'country_id' => 164],
    ['name' => 'Buskerud', 'country_id' => 164],
    ['name' => 'Finnmark', 'country_id' => 164],
    ['name' => 'Hedmark', 'country_id' => 164],
    ['name' => 'Hordaland', 'country_id' => 164],
    ['name' => 'Moere og Romsdal', 'country_id' => 164],
    ['name' => 'Nord Trondelag', 'country_id' => 164],
    ['name' => 'Nordland', 'country_id' => 164],
    ['name' => 'Oestfold', 'country_id' => 164],
    ['name' => 'Oppland', 'country_id' => 164],
    ['name' => 'Oslo', 'country_id' => 164],
    ['name' => 'Rogaland', 'country_id' => 164],
    ['name' => 'Soer Troendelag', 'country_id' => 164],
    ['name' => 'Sogn og Fjordane', 'country_id' => 164],
    ['name' => 'Stavern', 'country_id' => 164],
    ['name' => 'Sykkylven', 'country_id' => 164],
    ['name' => 'Telemark', 'country_id' => 164],
    ['name' => 'Troms', 'country_id' => 164],
    ['name' => 'Vest Agder', 'country_id' => 164],
    ['name' => 'Vestfold', 'country_id' => 164],
    ['name' => 'ÃƒÂ˜stfold', 'country_id' => 164],
];