<?php return [
    ['name' => 'Ariha', 'country_id' => 168],
    ['name' => 'Bayt Lahm', 'country_id' => 168],
    ['name' => 'Bethlehem', 'country_id' => 168],
    ['name' => 'Dayr-al-Balah', 'country_id' => 168],
    ['name' => 'Ghazzah', 'country_id' => 168],
    ['name' => 'Ghazzah ash-Shamaliyah', 'country_id' => 168],
    ['name' => 'Janin', 'country_id' => 168],
    ['name' => 'Khan Yunis', 'country_id' => 168],
    ['name' => 'Nabulus', 'country_id' => 168],
    ['name' => 'Qalqilyah', 'country_id' => 168],
    ['name' => 'Rafah', 'country_id' => 168],
    ['name' => 'Ram Allah wal-Birah', 'country_id' => 168],
    ['name' => 'Salfit', 'country_id' => 168],
    ['name' => 'Tubas', 'country_id' => 168],
    ['name' => 'Tulkarm', 'country_id' => 168],
    ['name' => 'al-Khalil', 'country_id' => 168],
    ['name' => 'al-Quds', 'country_id' => 168],
];