<?php return [
    ['name' => 'East New Britain', 'country_id' => 170],
    ['name' => 'East Sepik', 'country_id' => 170],
    ['name' => 'Eastern Highlands', 'country_id' => 170],
    ['name' => 'Enga', 'country_id' => 170],
    ['name' => 'Fly River', 'country_id' => 170],
    ['name' => 'Gulf', 'country_id' => 170],
    ['name' => 'Madang', 'country_id' => 170],
    ['name' => 'Manus', 'country_id' => 170],
    ['name' => 'Milne Bay', 'country_id' => 170],
    ['name' => 'Morobe', 'country_id' => 170],
    ['name' => 'National Capital District', 'country_id' => 170],
    ['name' => 'New Ireland', 'country_id' => 170],
    ['name' => 'North Solomons', 'country_id' => 170],
    ['name' => 'Oro', 'country_id' => 170],
    ['name' => 'Sandaun', 'country_id' => 170],
    ['name' => 'Simbu', 'country_id' => 170],
    ['name' => 'Southern Highlands', 'country_id' => 170],
    ['name' => 'West New Britain', 'country_id' => 170],
    ['name' => 'Western Highlands', 'country_id' => 170],
];