<?php return [
    ['name' => 'Alto Paraguay', 'country_id' => 171],
    ['name' => 'Alto Parana', 'country_id' => 171],
    ['name' => 'Amambay', 'country_id' => 171],
    ['name' => 'Asuncion', 'country_id' => 171],
    ['name' => 'Boqueron', 'country_id' => 171],
    ['name' => 'Caaguazu', 'country_id' => 171],
    ['name' => 'Caazapa', 'country_id' => 171],
    ['name' => 'Canendiyu', 'country_id' => 171],
    ['name' => 'Central', 'country_id' => 171],
    ['name' => 'Concepcion', 'country_id' => 171],
    ['name' => 'Cordillera', 'country_id' => 171],
    ['name' => 'Guaira', 'country_id' => 171],
    ['name' => 'Itapua', 'country_id' => 171],
    ['name' => 'Misiones', 'country_id' => 171],
    ['name' => 'Neembucu', 'country_id' => 171],
    ['name' => 'Paraguari', 'country_id' => 171],
    ['name' => 'Presidente Hayes', 'country_id' => 171],
    ['name' => 'San Pedro', 'country_id' => 171],
];