<?php return [
    ['name' => 'Amazonas', 'country_id' => 172],
    ['name' => 'Ancash', 'country_id' => 172],
    ['name' => 'Apurimac', 'country_id' => 172],
    ['name' => 'Arequipa', 'country_id' => 172],
    ['name' => 'Ayacucho', 'country_id' => 172],
    ['name' => 'Cajamarca', 'country_id' => 172],
    ['name' => 'Cusco', 'country_id' => 172],
    ['name' => 'Huancavelica', 'country_id' => 172],
    ['name' => 'Huanuco', 'country_id' => 172],
    ['name' => 'Ica', 'country_id' => 172],
    ['name' => 'Junin', 'country_id' => 172],
    ['name' => 'La Libertad', 'country_id' => 172],
    ['name' => 'Lambayeque', 'country_id' => 172],
    ['name' => 'Lima y Callao', 'country_id' => 172],
    ['name' => 'Loreto', 'country_id' => 172],
    ['name' => 'Madre de Dios', 'country_id' => 172],
    ['name' => 'Moquegua', 'country_id' => 172],
    ['name' => 'Pasco', 'country_id' => 172],
    ['name' => 'Piura', 'country_id' => 172],
    ['name' => 'Puno', 'country_id' => 172],
    ['name' => 'San Martin', 'country_id' => 172],
    ['name' => 'Tacna', 'country_id' => 172],
    ['name' => 'Tumbes', 'country_id' => 172],
    ['name' => 'Ucayali', 'country_id' => 172],
];