<?php return [
    ['name' => 'Batangas', 'country_id' => 173],
    ['name' => 'Bicol', 'country_id' => 173],
    ['name' => 'Bulacan', 'country_id' => 173],
    ['name' => 'Cagayan', 'country_id' => 173],
    ['name' => 'Caraga', 'country_id' => 173],
    ['name' => 'Central Luzon', 'country_id' => 173],
    ['name' => 'Central Mindanao', 'country_id' => 173],
    ['name' => 'Central Visayas', 'country_id' => 173],
    ['name' => 'Cordillera', 'country_id' => 173],
    ['name' => 'Davao', 'country_id' => 173],
    ['name' => 'Eastern Visayas', 'country_id' => 173],
    ['name' => 'Greater Metropolitan Area', 'country_id' => 173],
    ['name' => 'Ilocos', 'country_id' => 173],
    ['name' => 'Laguna', 'country_id' => 173],
    ['name' => 'Luzon', 'country_id' => 173],
    ['name' => 'Mactan', 'country_id' => 173],
    ['name' => 'Metropolitan Manila Area', 'country_id' => 173],
    ['name' => 'Muslim Mindanao', 'country_id' => 173],
    ['name' => 'Northern Mindanao', 'country_id' => 173],
    ['name' => 'Southern Mindanao', 'country_id' => 173],
    ['name' => 'Southern Tagalog', 'country_id' => 173],
    ['name' => 'Western Mindanao', 'country_id' => 173],
    ['name' => 'Western Visayas', 'country_id' => 173],
];