<?php return [
    ['name' => 'Biale Blota', 'country_id' => 175],
    ['name' => 'Dobroszyce', 'country_id' => 175],
    ['name' => 'Dolnoslaskie', 'country_id' => 175],
    ['name' => 'Dziekanow Lesny', 'country_id' => 175],
    ['name' => 'Hopowo', 'country_id' => 175],
    ['name' => 'Kartuzy', 'country_id' => 175],
    ['name' => 'Koscian', 'country_id' => 175],
    ['name' => 'Krakow', 'country_id' => 175],
    ['name' => 'Kujawsko-Pomorskie', 'country_id' => 175],
    ['name' => 'Lodzkie', 'country_id' => 175],
    ['name' => 'Lubelskie', 'country_id' => 175],
    ['name' => 'Lubuskie', 'country_id' => 175],
    ['name' => 'Malomice', 'country_id' => 175],
    ['name' => 'Malopolskie', 'country_id' => 175],
    ['name' => 'Mazowieckie', 'country_id' => 175],
    ['name' => 'Mirkow', 'country_id' => 175],
    ['name' => 'Opolskie', 'country_id' => 175],
    ['name' => 'Ostrowiec', 'country_id' => 175],
    ['name' => 'Podkarpackie', 'country_id' => 175],
    ['name' => 'Podlaskie', 'country_id' => 175],
    ['name' => 'Polska', 'country_id' => 175],
    ['name' => 'Pomorskie', 'country_id' => 175],
    ['name' => 'Poznan', 'country_id' => 175],
    ['name' => 'Pruszkow', 'country_id' => 175],
    ['name' => 'Rymanowska', 'country_id' => 175],
    ['name' => 'Rzeszow', 'country_id' => 175],
    ['name' => 'Slaskie', 'country_id' => 175],
    ['name' => 'Stare Pole', 'country_id' => 175],
    ['name' => 'Swietokrzyskie', 'country_id' => 175],
    ['name' => 'Warminsko-Mazurskie', 'country_id' => 175],
    ['name' => 'Warsaw', 'country_id' => 175],
    ['name' => 'Wejherowo', 'country_id' => 175],
    ['name' => 'Wielkopolskie', 'country_id' => 175],
    ['name' => 'Wroclaw', 'country_id' => 175],
    ['name' => 'Zachodnio-Pomorskie', 'country_id' => 175],
    ['name' => 'Zukowo', 'country_id' => 175],
];