<?php return [
    ['name' => 'Bagar Hat', 'country_id' => 18],
    ['name' => 'Bandarban', 'country_id' => 18],
    ['name' => 'Barguna', 'country_id' => 18],
    ['name' => 'Barisal', 'country_id' => 18],
    ['name' => 'Bhola', 'country_id' => 18],
    ['name' => 'Bogora', 'country_id' => 18],
    ['name' => 'Brahman Bariya', 'country_id' => 18],
    ['name' => 'Chandpur', 'country_id' => 18],
    ['name' => 'Chattagam', 'country_id' => 18],
    ['name' => 'Chittagong Division', 'country_id' => 18],
    ['name' => 'Chuadanga', 'country_id' => 18],
    ['name' => 'Dhaka', 'country_id' => 18],
    ['name' => 'Dinajpur', 'country_id' => 18],
    ['name' => 'Faridpur', 'country_id' => 18],
    ['name' => 'Feni', 'country_id' => 18],
    ['name' => 'Gaybanda', 'country_id' => 18],
    ['name' => 'Gazipur', 'country_id' => 18],
    ['name' => 'Gopalganj', 'country_id' => 18],
    ['name' => 'Habiganj', 'country_id' => 18],
    ['name' => 'Jaipur Hat', 'country_id' => 18],
    ['name' => 'Jamalpur', 'country_id' => 18],
    ['name' => 'Jessor', 'country_id' => 18],
    ['name' => 'Jhalakati', 'country_id' => 18],
    ['name' => 'Jhanaydah', 'country_id' => 18],
    ['name' => 'Khagrachhari', 'country_id' => 18],
    ['name' => 'Khulna', 'country_id' => 18],
    ['name' => 'Kishorganj', 'country_id' => 18],
    ['name' => 'Koks Bazar', 'country_id' => 18],
    ['name' => 'Komilla', 'country_id' => 18],
    ['name' => 'Kurigram', 'country_id' => 18],
    ['name' => 'Kushtiya', 'country_id' => 18],
    ['name' => 'Lakshmipur', 'country_id' => 18],
    ['name' => 'Lalmanir Hat', 'country_id' => 18],
    ['name' => 'Madaripur', 'country_id' => 18],
    ['name' => 'Magura', 'country_id' => 18],
    ['name' => 'Maimansingh', 'country_id' => 18],
    ['name' => 'Manikganj', 'country_id' => 18],
    ['name' => 'Maulvi Bazar', 'country_id' => 18],
    ['name' => 'Meherpur', 'country_id' => 18],
    ['name' => 'Munshiganj', 'country_id' => 18],
    ['name' => 'Naral', 'country_id' => 18],
    ['name' => 'Narayanganj', 'country_id' => 18],
    ['name' => 'Narsingdi', 'country_id' => 18],
    ['name' => 'Nator', 'country_id' => 18],
    ['name' => 'Naugaon', 'country_id' => 18],
    ['name' => 'Nawabganj', 'country_id' => 18],
    ['name' => 'Netrakona', 'country_id' => 18],
    ['name' => 'Nilphamari', 'country_id' => 18],
    ['name' => 'Noakhali', 'country_id' => 18],
    ['name' => 'Pabna', 'country_id' => 18],
    ['name' => 'Panchagarh', 'country_id' => 18],
    ['name' => 'Patuakhali', 'country_id' => 18],
    ['name' => 'Pirojpur', 'country_id' => 18],
    ['name' => 'Rajbari', 'country_id' => 18],
    ['name' => 'Rajshahi', 'country_id' => 18],
    ['name' => 'Rangamati', 'country_id' => 18],
    ['name' => 'Rangpur', 'country_id' => 18],
    ['name' => 'Satkhira', 'country_id' => 18],
    ['name' => 'Shariatpur', 'country_id' => 18],
    ['name' => 'Sherpur', 'country_id' => 18],
    ['name' => 'Silhat', 'country_id' => 18],
    ['name' => 'Sirajganj', 'country_id' => 18],
    ['name' => 'Sunamganj', 'country_id' => 18],
    ['name' => 'Tangayal', 'country_id' => 18],
    ['name' => 'Thakurgaon', 'country_id' => 18],
];