<?php return [
    ['name' => 'Adygeja', 'country_id' => 181],
    ['name' => 'Aga', 'country_id' => 181],
    ['name' => 'Alanija', 'country_id' => 181],
    ['name' => 'Altaj', 'country_id' => 181],
    ['name' => 'Amur', 'country_id' => 181],
    ['name' => 'Arhangelsk', 'country_id' => 181],
    ['name' => 'Astrahan', 'country_id' => 181],
    ['name' => 'Bashkortostan', 'country_id' => 181],
    ['name' => 'Belgorod', 'country_id' => 181],
    ['name' => 'Brjansk', 'country_id' => 181],
    ['name' => 'Burjatija', 'country_id' => 181],
    ['name' => 'Chechenija', 'country_id' => 181],
    ['name' => 'Cheljabinsk', 'country_id' => 181],
    ['name' => 'Chita', 'country_id' => 181],
    ['name' => 'Chukotka', 'country_id' => 181],
    ['name' => 'Chuvashija', 'country_id' => 181],
    ['name' => 'Dagestan', 'country_id' => 181],
    ['name' => 'Evenkija', 'country_id' => 181],
    ['name' => 'Gorno-Altaj', 'country_id' => 181],
    ['name' => 'Habarovsk', 'country_id' => 181],
    ['name' => 'Hakasija', 'country_id' => 181],
    ['name' => 'Hanty-Mansija', 'country_id' => 181],
    ['name' => 'Ingusetija', 'country_id' => 181],
    ['name' => 'Irkutsk', 'country_id' => 181],
    ['name' => 'Ivanovo', 'country_id' => 181],
    ['name' => 'Jamalo-Nenets', 'country_id' => 181],
    ['name' => 'Jaroslavl', 'country_id' => 181],
    ['name' => 'Jevrej', 'country_id' => 181],
    ['name' => 'Kabardino-Balkarija', 'country_id' => 181],
    ['name' => 'Kaliningrad', 'country_id' => 181],
    ['name' => 'Kalmykija', 'country_id' => 181],
    ['name' => 'Kaluga', 'country_id' => 181],
    ['name' => 'Kamchatka', 'country_id' => 181],
    ['name' => 'Karachaj-Cherkessija', 'country_id' => 181],
    ['name' => 'Karelija', 'country_id' => 181],
    ['name' => 'Kemerovo', 'country_id' => 181],
    ['name' => 'Khabarovskiy Kray', 'country_id' => 181],
    ['name' => 'Kirov', 'country_id' => 181],
    ['name' => 'Komi', 'country_id' => 181],
    ['name' => 'Komi-Permjakija', 'country_id' => 181],
    ['name' => 'Korjakija', 'country_id' => 181],
    ['name' => 'Kostroma', 'country_id' => 181],
    ['name' => 'Krasnodar', 'country_id' => 181],
    ['name' => 'Krasnojarsk', 'country_id' => 181],
    ['name' => 'Krasnoyarskiy Kray', 'country_id' => 181],
    ['name' => 'Kurgan', 'country_id' => 181],
    ['name' => 'Kursk', 'country_id' => 181],
    ['name' => 'Leningrad', 'country_id' => 181],
    ['name' => 'Lipeck', 'country_id' => 181],
    ['name' => 'Magadan', 'country_id' => 181],
    ['name' => 'Marij El', 'country_id' => 181],
    ['name' => 'Mordovija', 'country_id' => 181],
    ['name' => 'Moscow', 'country_id' => 181],
    ['name' => 'Moskovskaja Oblast', 'country_id' => 181],
    ['name' => 'Moskovskaya Oblast', 'country_id' => 181],
    ['name' => 'Moskva', 'country_id' => 181],
    ['name' => 'Murmansk', 'country_id' => 181],
    ['name' => 'Nenets', 'country_id' => 181],
    ['name' => 'Nizhnij Novgorod', 'country_id' => 181],
    ['name' => 'Novgorod', 'country_id' => 181],
    ['name' => 'Novokusnezk', 'country_id' => 181],
    ['name' => 'Novosibirsk', 'country_id' => 181],
    ['name' => 'Omsk', 'country_id' => 181],
    ['name' => 'Orenburg', 'country_id' => 181],
    ['name' => 'Orjol', 'country_id' => 181],
    ['name' => 'Penza', 'country_id' => 181],
    ['name' => 'Perm', 'country_id' => 181],
    ['name' => 'Primorje', 'country_id' => 181],
    ['name' => 'Pskov', 'country_id' => 181],
    ['name' => 'Pskovskaya Oblast', 'country_id' => 181],
    ['name' => 'Rjazan', 'country_id' => 181],
    ['name' => 'Rostov', 'country_id' => 181],
    ['name' => 'Saha', 'country_id' => 181],
    ['name' => 'Sahalin', 'country_id' => 181],
    ['name' => 'Samara', 'country_id' => 181],
    ['name' => 'Samarskaya', 'country_id' => 181],
    ['name' => 'Sankt-Peterburg', 'country_id' => 181],
    ['name' => 'Saratov', 'country_id' => 181],
    ['name' => 'Smolensk', 'country_id' => 181],
    ['name' => 'Stavropol', 'country_id' => 181],
    ['name' => 'Sverdlovsk', 'country_id' => 181],
    ['name' => 'Tajmyrija', 'country_id' => 181],
    ['name' => 'Tambov', 'country_id' => 181],
    ['name' => 'Tatarstan', 'country_id' => 181],
    ['name' => 'Tjumen', 'country_id' => 181],
    ['name' => 'Tomsk', 'country_id' => 181],
    ['name' => 'Tula', 'country_id' => 181],
    ['name' => 'Tver', 'country_id' => 181],
    ['name' => 'Tyva', 'country_id' => 181],
    ['name' => 'Udmurtija', 'country_id' => 181],
    ['name' => 'Uljanovsk', 'country_id' => 181],
    ['name' => 'Ulyanovskaya Oblast', 'country_id' => 181],
    ['name' => 'Ust-Orda', 'country_id' => 181],
    ['name' => 'Vladimir', 'country_id' => 181],
    ['name' => 'Volgograd', 'country_id' => 181],
    ['name' => 'Vologda', 'country_id' => 181],
    ['name' => 'Voronezh', 'country_id' => 181],
];