<?php return [
    ['name' => 'Christ Church Nichola Town', 'country_id' => 184],
    ['name' => 'Saint Anne Sandy Point', 'country_id' => 184],
    ['name' => 'Saint George Basseterre', 'country_id' => 184],
    ['name' => 'Saint George Gingerland', 'country_id' => 184],
    ['name' => 'Saint James Windward', 'country_id' => 184],
    ['name' => 'Saint John Capesterre', 'country_id' => 184],
    ['name' => 'Saint John Figtree', 'country_id' => 184],
    ['name' => 'Saint Mary Cayon', 'country_id' => 184],
    ['name' => 'Saint Paul Capesterre', 'country_id' => 184],
    ['name' => 'Saint Paul Charlestown', 'country_id' => 184],
    ['name' => 'Saint Peter Basseterre', 'country_id' => 184],
    ['name' => 'Saint Thomas Lowland', 'country_id' => 184],
    ['name' => 'Saint Thomas Middle Island', 'country_id' => 184],
    ['name' => 'Trinity Palmetto Point', 'country_id' => 184],
];