<?php return [
    ['name' => 'Al Khobar', 'country_id' => 191],
    ['name' => 'Aseer', 'country_id' => 191],
    ['name' => 'Ash Sharqiyah', 'country_id' => 191],
    ['name' => 'Asir', 'country_id' => 191],
    ['name' => 'Central Province', 'country_id' => 191],
    ['name' => 'Eastern Province', 'country_id' => 191],
    ['name' => 'Ha\'il', 'country_id' => 191],
    ['name' => 'Jawf', 'country_id' => 191],
    ['name' => 'Jizan', 'country_id' => 191],
    ['name' => 'Makkah', 'country_id' => 191],
    ['name' => 'Najran', 'country_id' => 191],
    ['name' => 'Qasim', 'country_id' => 191],
    ['name' => 'Tabuk', 'country_id' => 191],
    ['name' => 'Western Province', 'country_id' => 191],
    ['name' => 'al-Bahah', 'country_id' => 191],
    ['name' => 'al-Hudud-ash-Shamaliyah', 'country_id' => 191],
    ['name' => 'al-Madinah', 'country_id' => 191],
    ['name' => 'ar-Riyad', 'country_id' => 191],
];