<?php return [
    ['name' => 'Berat', 'country_id' => 2],
    ['name' => 'Bulqize', 'country_id' => 2],
    ['name' => 'Delvine', 'country_id' => 2],
    ['name' => 'Devoll', 'country_id' => 2],
    ['name' => 'Dibre', 'country_id' => 2],
    ['name' => 'Durres', 'country_id' => 2],
    ['name' => 'Elbasan', 'country_id' => 2],
    ['name' => 'Fier', 'country_id' => 2],
    ['name' => 'Gjirokaster', 'country_id' => 2],
    ['name' => 'Gramsh', 'country_id' => 2],
    ['name' => 'Has', 'country_id' => 2],
    ['name' => 'Kavaje', 'country_id' => 2],
    ['name' => 'Kolonje', 'country_id' => 2],
    ['name' => 'Korce', 'country_id' => 2],
    ['name' => 'Kruje', 'country_id' => 2],
    ['name' => 'Kucove', 'country_id' => 2],
    ['name' => 'Kukes', 'country_id' => 2],
    ['name' => 'Kurbin', 'country_id' => 2],
    ['name' => 'Lezhe', 'country_id' => 2],
    ['name' => 'Librazhd', 'country_id' => 2],
    ['name' => 'Lushnje', 'country_id' => 2],
    ['name' => 'Mallakaster', 'country_id' => 2],
    ['name' => 'Malsi e Madhe', 'country_id' => 2],
    ['name' => 'Mat', 'country_id' => 2],
    ['name' => 'Mirdite', 'country_id' => 2],
    ['name' => 'Peqin', 'country_id' => 2],
    ['name' => 'Permet', 'country_id' => 2],
    ['name' => 'Pogradec', 'country_id' => 2],
    ['name' => 'Puke', 'country_id' => 2],
    ['name' => 'Sarande', 'country_id' => 2],
    ['name' => 'Shkoder', 'country_id' => 2],
    ['name' => 'Skrapar', 'country_id' => 2],
    ['name' => 'Tepelene', 'country_id' => 2],
    ['name' => 'Tirane', 'country_id' => 2],
    ['name' => 'Tropoje', 'country_id' => 2],
    ['name' => 'Vlore', 'country_id' => 2],
];