<?php return [
    ['name' => 'Awdal', 'country_id' => 201],
    ['name' => 'Bakol', 'country_id' => 201],
    ['name' => 'Banadir', 'country_id' => 201],
    ['name' => 'Bari', 'country_id' => 201],
    ['name' => 'Bay', 'country_id' => 201],
    ['name' => 'Galgudug', 'country_id' => 201],
    ['name' => 'Gedo', 'country_id' => 201],
    ['name' => 'Hiran', 'country_id' => 201],
    ['name' => 'Jubbada Hose', 'country_id' => 201],
    ['name' => 'Jubbadha Dexe', 'country_id' => 201],
    ['name' => 'Mudug', 'country_id' => 201],
    ['name' => 'Nugal', 'country_id' => 201],
    ['name' => 'Sanag', 'country_id' => 201],
    ['name' => 'Shabellaha Dhexe', 'country_id' => 201],
    ['name' => 'Shabellaha Hose', 'country_id' => 201],
    ['name' => 'Togdher', 'country_id' => 201],
    ['name' => 'Woqoyi Galbed', 'country_id' => 201],
];