<?php return [
    ['name' => 'A Coruna', 'country_id' => 205],
    ['name' => 'Alacant', 'country_id' => 205],
    ['name' => 'Alava', 'country_id' => 205],
    ['name' => 'Albacete', 'country_id' => 205],
    ['name' => 'Almeria', 'country_id' => 205],
    ['name' => 'Andalucia', 'country_id' => 205],
    ['name' => 'Asturias', 'country_id' => 205],
    ['name' => 'Avila', 'country_id' => 205],
    ['name' => 'Badajoz', 'country_id' => 205],
    ['name' => 'Balears', 'country_id' => 205],
    ['name' => 'Barcelona', 'country_id' => 205],
    ['name' => 'Bertamirans', 'country_id' => 205],
    ['name' => 'Biscay', 'country_id' => 205],
    ['name' => 'Burgos', 'country_id' => 205],
    ['name' => 'Caceres', 'country_id' => 205],
    ['name' => 'Cadiz', 'country_id' => 205],
    ['name' => 'Cantabria', 'country_id' => 205],
    ['name' => 'Castello', 'country_id' => 205],
    ['name' => 'Catalunya', 'country_id' => 205],
    ['name' => 'Ceuta', 'country_id' => 205],
    ['name' => 'Ciudad Real', 'country_id' => 205],
    ['name' => 'Comunidad Autonoma de Canarias', 'country_id' => 205],
    ['name' => 'Comunidad Autonoma de Cataluna', 'country_id' => 205],
    ['name' => 'Comunidad Autonoma de Galicia', 'country_id' => 205],
    ['name' => 'Comunidad Autonoma de las Isla', 'country_id' => 205],
    ['name' => 'Comunidad Autonoma del Princip', 'country_id' => 205],
    ['name' => 'Comunidad Valenciana', 'country_id' => 205],
    ['name' => 'Cordoba', 'country_id' => 205],
    ['name' => 'Cuenca', 'country_id' => 205],
    ['name' => 'Gipuzkoa', 'country_id' => 205],
    ['name' => 'Girona', 'country_id' => 205],
    ['name' => 'Granada', 'country_id' => 205],
    ['name' => 'Guadalajara', 'country_id' => 205],
    ['name' => 'Guipuzcoa', 'country_id' => 205],
    ['name' => 'Huelva', 'country_id' => 205],
    ['name' => 'Huesca', 'country_id' => 205],
    ['name' => 'Jaen', 'country_id' => 205],
    ['name' => 'La Rioja', 'country_id' => 205],
    ['name' => 'Las Palmas', 'country_id' => 205],
    ['name' => 'Leon', 'country_id' => 205],
    ['name' => 'Lerida', 'country_id' => 205],
    ['name' => 'Lleida', 'country_id' => 205],
    ['name' => 'Lugo', 'country_id' => 205],
    ['name' => 'Madrid', 'country_id' => 205],
    ['name' => 'Malaga', 'country_id' => 205],
    ['name' => 'Melilla', 'country_id' => 205],
    ['name' => 'Murcia', 'country_id' => 205],
    ['name' => 'Navarra', 'country_id' => 205],
    ['name' => 'Ourense', 'country_id' => 205],
    ['name' => 'Pais Vasco', 'country_id' => 205],
    ['name' => 'Palencia', 'country_id' => 205],
    ['name' => 'Pontevedra', 'country_id' => 205],
    ['name' => 'Salamanca', 'country_id' => 205],
    ['name' => 'Santa Cruz de Tenerife', 'country_id' => 205],
    ['name' => 'Segovia', 'country_id' => 205],
    ['name' => 'Sevilla', 'country_id' => 205],
    ['name' => 'Soria', 'country_id' => 205],
    ['name' => 'Tarragona', 'country_id' => 205],
    ['name' => 'Tenerife', 'country_id' => 205],
    ['name' => 'Teruel', 'country_id' => 205],
    ['name' => 'Toledo', 'country_id' => 205],
    ['name' => 'Valencia', 'country_id' => 205],
    ['name' => 'Valladolid', 'country_id' => 205],
    ['name' => 'Vizcaya', 'country_id' => 205],
    ['name' => 'Zamora', 'country_id' => 205],
    ['name' => 'Zaragoza', 'country_id' => 205],
];