<?php return [
    ['name' => 'Amparai', 'country_id' => 206],
    ['name' => 'Anuradhapuraya', 'country_id' => 206],
    ['name' => 'Badulla', 'country_id' => 206],
    ['name' => 'Boralesgamuwa', 'country_id' => 206],
    ['name' => 'Colombo', 'country_id' => 206],
    ['name' => 'Galla', 'country_id' => 206],
    ['name' => 'Gampaha', 'country_id' => 206],
    ['name' => 'Hambantota', 'country_id' => 206],
    ['name' => 'Kalatura', 'country_id' => 206],
    ['name' => 'Kegalla', 'country_id' => 206],
    ['name' => 'Kilinochchi', 'country_id' => 206],
    ['name' => 'Kurunegala', 'country_id' => 206],
    ['name' => 'Madakalpuwa', 'country_id' => 206],
    ['name' => 'Maha Nuwara', 'country_id' => 206],
    ['name' => 'Malwana', 'country_id' => 206],
    ['name' => 'Mannarama', 'country_id' => 206],
    ['name' => 'Matale', 'country_id' => 206],
    ['name' => 'Matara', 'country_id' => 206],
    ['name' => 'Monaragala', 'country_id' => 206],
    ['name' => 'Mullaitivu', 'country_id' => 206],
    ['name' => 'North Eastern Province', 'country_id' => 206],
    ['name' => 'North Western Province', 'country_id' => 206],
    ['name' => 'Nuwara Eliya', 'country_id' => 206],
    ['name' => 'Polonnaruwa', 'country_id' => 206],
    ['name' => 'Puttalama', 'country_id' => 206],
    ['name' => 'Ratnapuraya', 'country_id' => 206],
    ['name' => 'Southern Province', 'country_id' => 206],
    ['name' => 'Tirikunamalaya', 'country_id' => 206],
    ['name' => 'Tuscany', 'country_id' => 206],
    ['name' => 'Vavuniyawa', 'country_id' => 206],
    ['name' => 'Western Province', 'country_id' => 206],
    ['name' => 'Yapanaya', 'country_id' => 206],
    ['name' => 'kadawatha', 'country_id' => 206],
];