<?php return [
    ['name' => 'A\'ali-an-Nil', 'country_id' => 207],
    ['name' => 'Bahr-al-Jabal', 'country_id' => 207],
    ['name' => 'Central Equatoria', 'country_id' => 207],
    ['name' => 'Gharb Bahr-al-Ghazal', 'country_id' => 207],
    ['name' => 'Gharb Darfur', 'country_id' => 207],
    ['name' => 'Gharb Kurdufan', 'country_id' => 207],
    ['name' => 'Gharb-al-Istiwa\'iyah', 'country_id' => 207],
    ['name' => 'Janub Darfur', 'country_id' => 207],
    ['name' => 'Janub Kurdufan', 'country_id' => 207],
    ['name' => 'Junqali', 'country_id' => 207],
    ['name' => 'Kassala', 'country_id' => 207],
    ['name' => 'Nahr-an-Nil', 'country_id' => 207],
    ['name' => 'Shamal Bahr-al-Ghazal', 'country_id' => 207],
    ['name' => 'Shamal Darfur', 'country_id' => 207],
    ['name' => 'Shamal Kurdufan', 'country_id' => 207],
    ['name' => 'Sharq-al-Istiwa\'iyah', 'country_id' => 207],
    ['name' => 'Sinnar', 'country_id' => 207],
    ['name' => 'Warab', 'country_id' => 207],
    ['name' => 'Wilayat al Khartum', 'country_id' => 207],
    ['name' => 'al-Bahr-al-Ahmar', 'country_id' => 207],
    ['name' => 'al-Buhayrat', 'country_id' => 207],
    ['name' => 'al-Jazirah', 'country_id' => 207],
    ['name' => 'al-Khartum', 'country_id' => 207],
    ['name' => 'al-Qadarif', 'country_id' => 207],
    ['name' => 'al-Wahdah', 'country_id' => 207],
    ['name' => 'an-Nil-al-Abyad', 'country_id' => 207],
    ['name' => 'an-Nil-al-Azraq', 'country_id' => 207],
    ['name' => 'ash-Shamaliyah', 'country_id' => 207],
];