<?php return [
    ['name' => 'Antwerpen', 'country_id' => 21],
    ['name' => 'Berchem', 'country_id' => 21],
    ['name' => 'Brabant', 'country_id' => 21],
    ['name' => 'Brabant Wallon', 'country_id' => 21],
    ['name' => 'Brussel', 'country_id' => 21],
    ['name' => 'East Flanders', 'country_id' => 21],
    ['name' => 'Hainaut', 'country_id' => 21],
    ['name' => 'Liege', 'country_id' => 21],
    ['name' => 'Limburg', 'country_id' => 21],
    ['name' => 'Luxembourg', 'country_id' => 21],
    ['name' => 'Namur', 'country_id' => 21],
    ['name' => 'Ontario', 'country_id' => 21],
    ['name' => 'Oost-Vlaanderen', 'country_id' => 21],
    ['name' => 'Provincie Brabant', 'country_id' => 21],
    ['name' => 'Vlaams-Brabant', 'country_id' => 21],
    ['name' => 'Wallonne', 'country_id' => 21],
    ['name' => 'West-Vlaanderen', 'country_id' => 21],
];