<?php return [
    ['name' => 'Alvsborgs Lan', 'country_id' => 211],
    ['name' => 'Angermanland', 'country_id' => 211],
    ['name' => 'Blekinge', 'country_id' => 211],
    ['name' => 'Bohuslan', 'country_id' => 211],
    ['name' => 'Dalarna', 'country_id' => 211],
    ['name' => 'Gavleborg', 'country_id' => 211],
    ['name' => 'Gaza', 'country_id' => 211],
    ['name' => 'Gotland', 'country_id' => 211],
    ['name' => 'Halland', 'country_id' => 211],
    ['name' => 'Jamtland', 'country_id' => 211],
    ['name' => 'Jonkoping', 'country_id' => 211],
    ['name' => 'Kalmar', 'country_id' => 211],
    ['name' => 'Kristianstads', 'country_id' => 211],
    ['name' => 'Kronoberg', 'country_id' => 211],
    ['name' => 'Norrbotten', 'country_id' => 211],
    ['name' => 'Orebro', 'country_id' => 211],
    ['name' => 'Ostergotland', 'country_id' => 211],
    ['name' => 'Saltsjo-Boo', 'country_id' => 211],
    ['name' => 'Skane', 'country_id' => 211],
    ['name' => 'Smaland', 'country_id' => 211],
    ['name' => 'Sodermanland', 'country_id' => 211],
    ['name' => 'Stockholm', 'country_id' => 211],
    ['name' => 'Uppsala', 'country_id' => 211],
    ['name' => 'Varmland', 'country_id' => 211],
    ['name' => 'Vasterbotten', 'country_id' => 211],
    ['name' => 'Vastergotland', 'country_id' => 211],
    ['name' => 'Vasternorrland', 'country_id' => 211],
    ['name' => 'Vastmanland', 'country_id' => 211],
    ['name' => 'Vastra Gotaland', 'country_id' => 211],
];