<?php return [
    ['name' => 'Aargau', 'country_id' => 212],
    ['name' => 'Appenzell Inner-Rhoden', 'country_id' => 212],
    ['name' => 'Appenzell-Ausser Rhoden', 'country_id' => 212],
    ['name' => 'Basel-Landschaft', 'country_id' => 212],
    ['name' => 'Basel-Stadt', 'country_id' => 212],
    ['name' => 'Bern', 'country_id' => 212],
    ['name' => 'Canton Ticino', 'country_id' => 212],
    ['name' => 'Fribourg', 'country_id' => 212],
    ['name' => 'Geneve', 'country_id' => 212],
    ['name' => 'Glarus', 'country_id' => 212],
    ['name' => 'Graubunden', 'country_id' => 212],
    ['name' => 'Heerbrugg', 'country_id' => 212],
    ['name' => 'Jura', 'country_id' => 212],
    ['name' => 'Kanton Aargau', 'country_id' => 212],
    ['name' => 'Luzern', 'country_id' => 212],
    ['name' => 'Morbio Inferiore', 'country_id' => 212],
    ['name' => 'Muhen', 'country_id' => 212],
    ['name' => 'Neuchatel', 'country_id' => 212],
    ['name' => 'Nidwalden', 'country_id' => 212],
    ['name' => 'Obwalden', 'country_id' => 212],
    ['name' => 'Sankt Gallen', 'country_id' => 212],
    ['name' => 'Schaffhausen', 'country_id' => 212],
    ['name' => 'Schwyz', 'country_id' => 212],
    ['name' => 'Solothurn', 'country_id' => 212],
    ['name' => 'Thurgau', 'country_id' => 212],
    ['name' => 'Ticino', 'country_id' => 212],
    ['name' => 'Uri', 'country_id' => 212],
    ['name' => 'Valais', 'country_id' => 212],
    ['name' => 'Vaud', 'country_id' => 212],
    ['name' => 'Vauffelin', 'country_id' => 212],
    ['name' => 'Zug', 'country_id' => 212],
    ['name' => 'Zurich', 'country_id' => 212],
];