<?php return [
    ['name' => 'Changhwa', 'country_id' => 214],
    ['name' => 'Chiayi Hsien', 'country_id' => 214],
    ['name' => 'Chiayi Shih', 'country_id' => 214],
    ['name' => 'Eastern Taipei', 'country_id' => 214],
    ['name' => 'Hsinchu Hsien', 'country_id' => 214],
    ['name' => 'Hsinchu Shih', 'country_id' => 214],
    ['name' => 'Hualien', 'country_id' => 214],
    ['name' => 'Ilan', 'country_id' => 214],
    ['name' => 'Kaohsiung Hsien', 'country_id' => 214],
    ['name' => 'Kaohsiung Shih', 'country_id' => 214],
    ['name' => 'Keelung Shih', 'country_id' => 214],
    ['name' => 'Kinmen', 'country_id' => 214],
    ['name' => 'Miaoli', 'country_id' => 214],
    ['name' => 'Nantou', 'country_id' => 214],
    ['name' => 'Northern Taiwan', 'country_id' => 214],
    ['name' => 'Penghu', 'country_id' => 214],
    ['name' => 'Pingtung', 'country_id' => 214],
    ['name' => 'Taichung', 'country_id' => 214],
    ['name' => 'Taichung Hsien', 'country_id' => 214],
    ['name' => 'Taichung Shih', 'country_id' => 214],
    ['name' => 'Tainan Hsien', 'country_id' => 214],
    ['name' => 'Tainan Shih', 'country_id' => 214],
    ['name' => 'Taipei Hsien', 'country_id' => 214],
    ['name' => 'Taipei Shih / Taipei Hsien', 'country_id' => 214],
    ['name' => 'Taitung', 'country_id' => 214],
    ['name' => 'Taoyuan', 'country_id' => 214],
    ['name' => 'Yilan', 'country_id' => 214],
    ['name' => 'Yun-Lin Hsien', 'country_id' => 214],
    ['name' => 'Yunlin', 'country_id' => 214],
];