<?php return [
    ['name' => 'Arusha', 'country_id' => 216],
    ['name' => 'Dar es Salaam', 'country_id' => 216],
    ['name' => 'Dodoma', 'country_id' => 216],
    ['name' => 'Iringa', 'country_id' => 216],
    ['name' => 'Kagera', 'country_id' => 216],
    ['name' => 'Kigoma', 'country_id' => 216],
    ['name' => 'Kilimanjaro', 'country_id' => 216],
    ['name' => 'Lindi', 'country_id' => 216],
    ['name' => 'Mara', 'country_id' => 216],
    ['name' => 'Mbeya', 'country_id' => 216],
    ['name' => 'Morogoro', 'country_id' => 216],
    ['name' => 'Mtwara', 'country_id' => 216],
    ['name' => 'Mwanza', 'country_id' => 216],
    ['name' => 'Pwani', 'country_id' => 216],
    ['name' => 'Rukwa', 'country_id' => 216],
    ['name' => 'Ruvuma', 'country_id' => 216],
    ['name' => 'Shinyanga', 'country_id' => 216],
    ['name' => 'Singida', 'country_id' => 216],
    ['name' => 'Tabora', 'country_id' => 216],
    ['name' => 'Tanga', 'country_id' => 216],
    ['name' => 'Zanzibar and Pemba', 'country_id' => 216],
];