<?php return [
    ['name' => 'Amnat Charoen', 'country_id' => 217],
    ['name' => 'Ang Thong', 'country_id' => 217],
    ['name' => 'Bangkok', 'country_id' => 217],
    ['name' => 'Buri Ram', 'country_id' => 217],
    ['name' => 'Chachoengsao', 'country_id' => 217],
    ['name' => 'Chai Nat', 'country_id' => 217],
    ['name' => 'Chaiyaphum', 'country_id' => 217],
    ['name' => 'Changwat Chaiyaphum', 'country_id' => 217],
    ['name' => 'Chanthaburi', 'country_id' => 217],
    ['name' => 'Chiang Mai', 'country_id' => 217],
    ['name' => 'Chiang Rai', 'country_id' => 217],
    ['name' => 'Chon Buri', 'country_id' => 217],
    ['name' => 'Chumphon', 'country_id' => 217],
    ['name' => 'Kalasin', 'country_id' => 217],
    ['name' => 'Kamphaeng Phet', 'country_id' => 217],
    ['name' => 'Kanchanaburi', 'country_id' => 217],
    ['name' => 'Khon Kaen', 'country_id' => 217],
    ['name' => 'Krabi', 'country_id' => 217],
    ['name' => 'Krung Thep', 'country_id' => 217],
    ['name' => 'Lampang', 'country_id' => 217],
    ['name' => 'Lamphun', 'country_id' => 217],
    ['name' => 'Loei', 'country_id' => 217],
    ['name' => 'Lop Buri', 'country_id' => 217],
    ['name' => 'Mae Hong Son', 'country_id' => 217],
    ['name' => 'Maha Sarakham', 'country_id' => 217],
    ['name' => 'Mukdahan', 'country_id' => 217],
    ['name' => 'Nakhon Nayok', 'country_id' => 217],
    ['name' => 'Nakhon Pathom', 'country_id' => 217],
    ['name' => 'Nakhon Phanom', 'country_id' => 217],
    ['name' => 'Nakhon Ratchasima', 'country_id' => 217],
    ['name' => 'Nakhon Sawan', 'country_id' => 217],
    ['name' => 'Nakhon Si Thammarat', 'country_id' => 217],
    ['name' => 'Nan', 'country_id' => 217],
    ['name' => 'Narathiwat', 'country_id' => 217],
    ['name' => 'Nong Bua Lam Phu', 'country_id' => 217],
    ['name' => 'Nong Khai', 'country_id' => 217],
    ['name' => 'Nonthaburi', 'country_id' => 217],
    ['name' => 'Pathum Thani', 'country_id' => 217],
    ['name' => 'Pattani', 'country_id' => 217],
    ['name' => 'Phangnga', 'country_id' => 217],
    ['name' => 'Phatthalung', 'country_id' => 217],
    ['name' => 'Phayao', 'country_id' => 217],
    ['name' => 'Phetchabun', 'country_id' => 217],
    ['name' => 'Phetchaburi', 'country_id' => 217],
    ['name' => 'Phichit', 'country_id' => 217],
    ['name' => 'Phitsanulok', 'country_id' => 217],
    ['name' => 'Phra Nakhon Si Ayutthaya', 'country_id' => 217],
    ['name' => 'Phrae', 'country_id' => 217],
    ['name' => 'Phuket', 'country_id' => 217],
    ['name' => 'Prachin Buri', 'country_id' => 217],
    ['name' => 'Prachuap Khiri Khan', 'country_id' => 217],
    ['name' => 'Ranong', 'country_id' => 217],
    ['name' => 'Ratchaburi', 'country_id' => 217],
    ['name' => 'Rayong', 'country_id' => 217],
    ['name' => 'Roi Et', 'country_id' => 217],
    ['name' => 'Sa Kaeo', 'country_id' => 217],
    ['name' => 'Sakon Nakhon', 'country_id' => 217],
    ['name' => 'Samut Prakan', 'country_id' => 217],
    ['name' => 'Samut Sakhon', 'country_id' => 217],
    ['name' => 'Samut Songkhran', 'country_id' => 217],
    ['name' => 'Saraburi', 'country_id' => 217],
    ['name' => 'Satun', 'country_id' => 217],
    ['name' => 'Si Sa Ket', 'country_id' => 217],
    ['name' => 'Sing Buri', 'country_id' => 217],
    ['name' => 'Songkhla', 'country_id' => 217],
    ['name' => 'Sukhothai', 'country_id' => 217],
    ['name' => 'Suphan Buri', 'country_id' => 217],
    ['name' => 'Surat Thani', 'country_id' => 217],
    ['name' => 'Surin', 'country_id' => 217],
    ['name' => 'Tak', 'country_id' => 217],
    ['name' => 'Trang', 'country_id' => 217],
    ['name' => 'Trat', 'country_id' => 217],
    ['name' => 'Ubon Ratchathani', 'country_id' => 217],
    ['name' => 'Udon Thani', 'country_id' => 217],
    ['name' => 'Uthai Thani', 'country_id' => 217],
    ['name' => 'Uttaradit', 'country_id' => 217],
    ['name' => 'Yala', 'country_id' => 217],
    ['name' => 'Yasothon', 'country_id' => 217],
];