<?php return [
    ['name' => 'Aryanah', 'country_id' => 222],
    ['name' => 'Bajah', 'country_id' => 222],
    ['name' => 'Bin \'Arus', 'country_id' => 222],
    ['name' => 'Binzart', 'country_id' => 222],
    ['name' => 'Gouvernorat de Ariana', 'country_id' => 222],
    ['name' => 'Gouvernorat de Nabeul', 'country_id' => 222],
    ['name' => 'Gouvernorat de Sousse', 'country_id' => 222],
    ['name' => 'Hammamet Yasmine', 'country_id' => 222],
    ['name' => 'Jundubah', 'country_id' => 222],
    ['name' => 'Madaniyin', 'country_id' => 222],
    ['name' => 'Manubah', 'country_id' => 222],
    ['name' => 'Monastir', 'country_id' => 222],
    ['name' => 'Nabul', 'country_id' => 222],
    ['name' => 'Qabis', 'country_id' => 222],
    ['name' => 'Qafsah', 'country_id' => 222],
    ['name' => 'Qibili', 'country_id' => 222],
    ['name' => 'Safaqis', 'country_id' => 222],
    ['name' => 'Sfax', 'country_id' => 222],
    ['name' => 'Sidi Bu Zayd', 'country_id' => 222],
    ['name' => 'Silyanah', 'country_id' => 222],
    ['name' => 'Susah', 'country_id' => 222],
    ['name' => 'Tatawin', 'country_id' => 222],
    ['name' => 'Tawzar', 'country_id' => 222],
    ['name' => 'Tunis', 'country_id' => 222],
    ['name' => 'Zaghwan', 'country_id' => 222],
    ['name' => 'al-Kaf', 'country_id' => 222],
    ['name' => 'al-Mahdiyah', 'country_id' => 222],
    ['name' => 'al-Munastir', 'country_id' => 222],
    ['name' => 'al-Qasrayn', 'country_id' => 222],
    ['name' => 'al-Qayrawan', 'country_id' => 222],
];