<?php return [
    ['name' => 'Aberdeen', 'country_id' => 230],
    ['name' => 'Aberdeenshire', 'country_id' => 230],
    ['name' => 'Argyll', 'country_id' => 230],
    ['name' => 'Armagh', 'country_id' => 230],
    ['name' => 'Bedfordshire', 'country_id' => 230],
    ['name' => 'Belfast', 'country_id' => 230],
    ['name' => 'Berkshire', 'country_id' => 230],
    ['name' => 'Birmingham', 'country_id' => 230],
    ['name' => 'Brechin', 'country_id' => 230],
    ['name' => 'Bridgnorth', 'country_id' => 230],
    ['name' => 'Bristol', 'country_id' => 230],
    ['name' => 'Buckinghamshire', 'country_id' => 230],
    ['name' => 'Cambridge', 'country_id' => 230],
    ['name' => 'Cambridgeshire', 'country_id' => 230],
    ['name' => 'Channel Islands', 'country_id' => 230],
    ['name' => 'Cheshire', 'country_id' => 230],
    ['name' => 'Cleveland', 'country_id' => 230],
    ['name' => 'Co Fermanagh', 'country_id' => 230],
    ['name' => 'Conwy', 'country_id' => 230],
    ['name' => 'Cornwall', 'country_id' => 230],
    ['name' => 'Coventry', 'country_id' => 230],
    ['name' => 'Craven Arms', 'country_id' => 230],
    ['name' => 'Cumbria', 'country_id' => 230],
    ['name' => 'Denbighshire', 'country_id' => 230],
    ['name' => 'Derby', 'country_id' => 230],
    ['name' => 'Derbyshire', 'country_id' => 230],
    ['name' => 'Devon', 'country_id' => 230],
    ['name' => 'Dial Code Dungannon', 'country_id' => 230],
    ['name' => 'Didcot', 'country_id' => 230],
    ['name' => 'Dorset', 'country_id' => 230],
    ['name' => 'Dunbartonshire', 'country_id' => 230],
    ['name' => 'Durham', 'country_id' => 230],
    ['name' => 'East Dunbartonshire', 'country_id' => 230],
    ['name' => 'East Lothian', 'country_id' => 230],
    ['name' => 'East Midlands', 'country_id' => 230],
    ['name' => 'East Sussex', 'country_id' => 230],
    ['name' => 'East Yorkshire', 'country_id' => 230],
    ['name' => 'England', 'country_id' => 230],
    ['name' => 'Essex', 'country_id' => 230],
    ['name' => 'Fermanagh', 'country_id' => 230],
    ['name' => 'Fife', 'country_id' => 230],
    ['name' => 'Flintshire', 'country_id' => 230],
    ['name' => 'Fulham', 'country_id' => 230],
    ['name' => 'Gainsborough', 'country_id' => 230],
    ['name' => 'Glocestershire', 'country_id' => 230],
    ['name' => 'Gwent', 'country_id' => 230],
    ['name' => 'Hampshire', 'country_id' => 230],
    ['name' => 'Hants', 'country_id' => 230],
    ['name' => 'Herefordshire', 'country_id' => 230],
    ['name' => 'Hertfordshire', 'country_id' => 230],
    ['name' => 'Ireland', 'country_id' => 230],
    ['name' => 'Isle Of Man', 'country_id' => 230],
    ['name' => 'Isle of Wight', 'country_id' => 230],
    ['name' => 'Kenford', 'country_id' => 230],
    ['name' => 'Kent', 'country_id' => 230],
    ['name' => 'Kilmarnock', 'country_id' => 230],
    ['name' => 'Lanarkshire', 'country_id' => 230],
    ['name' => 'Lancashire', 'country_id' => 230],
    ['name' => 'Leicestershire', 'country_id' => 230],
    ['name' => 'Lincolnshire', 'country_id' => 230],
    ['name' => 'Llanymynech', 'country_id' => 230],
    ['name' => 'London', 'country_id' => 230],
    ['name' => 'Ludlow', 'country_id' => 230],
    ['name' => 'Manchester', 'country_id' => 230],
    ['name' => 'Mayfair', 'country_id' => 230],
    ['name' => 'Merseyside', 'country_id' => 230],
    ['name' => 'Mid Glamorgan', 'country_id' => 230],
    ['name' => 'Middlesex', 'country_id' => 230],
    ['name' => 'Mildenhall', 'country_id' => 230],
    ['name' => 'Monmouthshire', 'country_id' => 230],
    ['name' => 'Newton Stewart', 'country_id' => 230],
    ['name' => 'Norfolk', 'country_id' => 230],
    ['name' => 'North Humberside', 'country_id' => 230],
    ['name' => 'North Yorkshire', 'country_id' => 230],
    ['name' => 'Northamptonshire', 'country_id' => 230],
    ['name' => 'Northants', 'country_id' => 230],
    ['name' => 'Northern Ireland', 'country_id' => 230],
    ['name' => 'Northumberland', 'country_id' => 230],
    ['name' => 'Nottinghamshire', 'country_id' => 230],
    ['name' => 'Oxford', 'country_id' => 230],
    ['name' => 'Powys', 'country_id' => 230],
    ['name' => 'Roos-shire', 'country_id' => 230],
    ['name' => 'SUSSEX', 'country_id' => 230],
    ['name' => 'Sark', 'country_id' => 230],
    ['name' => 'Scotland', 'country_id' => 230],
    ['name' => 'Scottish Borders', 'country_id' => 230],
    ['name' => 'Shropshire', 'country_id' => 230],
    ['name' => 'Somerset', 'country_id' => 230],
    ['name' => 'South Glamorgan', 'country_id' => 230],
    ['name' => 'South Wales', 'country_id' => 230],
    ['name' => 'South Yorkshire', 'country_id' => 230],
    ['name' => 'Southwell', 'country_id' => 230],
    ['name' => 'Staffordshire', 'country_id' => 230],
    ['name' => 'Strabane', 'country_id' => 230],
    ['name' => 'Suffolk', 'country_id' => 230],
    ['name' => 'Surrey', 'country_id' => 230],
    ['name' => 'Sussex', 'country_id' => 230],
    ['name' => 'Twickenham', 'country_id' => 230],
    ['name' => 'Tyne and Wear', 'country_id' => 230],
    ['name' => 'Tyrone', 'country_id' => 230],
    ['name' => 'Utah', 'country_id' => 230],
    ['name' => 'Wales', 'country_id' => 230],
    ['name' => 'Warwickshire', 'country_id' => 230],
    ['name' => 'West Lothian', 'country_id' => 230],
    ['name' => 'West Midlands', 'country_id' => 230],
    ['name' => 'West Sussex', 'country_id' => 230],
    ['name' => 'West Yorkshire', 'country_id' => 230],
    ['name' => 'Whissendine', 'country_id' => 230],
    ['name' => 'Wiltshire', 'country_id' => 230],
    ['name' => 'Wokingham', 'country_id' => 230],
    ['name' => 'Worcestershire', 'country_id' => 230],
    ['name' => 'Wrexham', 'country_id' => 230],
    ['name' => 'Wurttemberg', 'country_id' => 230],
    ['name' => 'Yorkshire', 'country_id' => 230],
];