<?php return [
    ['name' => 'Alabama', 'country_id' => 231],
    ['name' => 'Alaska', 'country_id' => 231],
    ['name' => 'Arizona', 'country_id' => 231],
    ['name' => 'Arkansas', 'country_id' => 231],
    ['name' => 'Byram', 'country_id' => 231],
    ['name' => 'California', 'country_id' => 231],
    ['name' => 'Cokato', 'country_id' => 231],
    ['name' => 'Colorado', 'country_id' => 231],
    ['name' => 'Connecticut', 'country_id' => 231],
    ['name' => 'Delaware', 'country_id' => 231],
    ['name' => 'District of Columbia', 'country_id' => 231],
    ['name' => 'Florida', 'country_id' => 231],
    ['name' => 'Georgia', 'country_id' => 231],
    ['name' => 'Hawaii', 'country_id' => 231],
    ['name' => 'Idaho', 'country_id' => 231],
    ['name' => 'Illinois', 'country_id' => 231],
    ['name' => 'Indiana', 'country_id' => 231],
    ['name' => 'Iowa', 'country_id' => 231],
    ['name' => 'Kansas', 'country_id' => 231],
    ['name' => 'Kentucky', 'country_id' => 231],
    ['name' => 'Louisiana', 'country_id' => 231],
    ['name' => 'Lowa', 'country_id' => 231],
    ['name' => 'Maine', 'country_id' => 231],
    ['name' => 'Maryland', 'country_id' => 231],
    ['name' => 'Massachusetts', 'country_id' => 231],
    ['name' => 'Medfield', 'country_id' => 231],
    ['name' => 'Michigan', 'country_id' => 231],
    ['name' => 'Minnesota', 'country_id' => 231],
    ['name' => 'Mississippi', 'country_id' => 231],
    ['name' => 'Missouri', 'country_id' => 231],
    ['name' => 'Montana', 'country_id' => 231],
    ['name' => 'Nebraska', 'country_id' => 231],
    ['name' => 'Nevada', 'country_id' => 231],
    ['name' => 'New Hampshire', 'country_id' => 231],
    ['name' => 'New Jersey', 'country_id' => 231],
    ['name' => 'New Jersy', 'country_id' => 231],
    ['name' => 'New Mexico', 'country_id' => 231],
    ['name' => 'New York', 'country_id' => 231],
    ['name' => 'North Carolina', 'country_id' => 231],
    ['name' => 'North Dakota', 'country_id' => 231],
    ['name' => 'Ohio', 'country_id' => 231],
    ['name' => 'Oklahoma', 'country_id' => 231],
    ['name' => 'Ontario', 'country_id' => 231],
    ['name' => 'Oregon', 'country_id' => 231],
    ['name' => 'Pennsylvania', 'country_id' => 231],
    ['name' => 'Ramey', 'country_id' => 231],
    ['name' => 'Rhode Island', 'country_id' => 231],
    ['name' => 'South Carolina', 'country_id' => 231],
    ['name' => 'South Dakota', 'country_id' => 231],
    ['name' => 'Sublimity', 'country_id' => 231],
    ['name' => 'Tennessee', 'country_id' => 231],
    ['name' => 'Texas', 'country_id' => 231],
    ['name' => 'Trimble', 'country_id' => 231],
    ['name' => 'Utah', 'country_id' => 231],
    ['name' => 'Vermont', 'country_id' => 231],
    ['name' => 'Virginia', 'country_id' => 231],
    ['name' => 'Washington', 'country_id' => 231],
    ['name' => 'West Virginia', 'country_id' => 231],
    ['name' => 'Wisconsin', 'country_id' => 231],
    ['name' => 'Wyoming', 'country_id' => 231],
];