<?php return [
    ['name' => 'Artigas', 'country_id' => 233],
    ['name' => 'Canelones', 'country_id' => 233],
    ['name' => 'Cerro Largo', 'country_id' => 233],
    ['name' => 'Colonia', 'country_id' => 233],
    ['name' => 'Durazno', 'country_id' => 233],
    ['name' => 'FLorida', 'country_id' => 233],
    ['name' => 'Flores', 'country_id' => 233],
    ['name' => 'Lavalleja', 'country_id' => 233],
    ['name' => 'Maldonado', 'country_id' => 233],
    ['name' => 'Montevideo', 'country_id' => 233],
    ['name' => 'Paysandu', 'country_id' => 233],
    ['name' => 'Rio Negro', 'country_id' => 233],
    ['name' => 'Rivera', 'country_id' => 233],
    ['name' => 'Rocha', 'country_id' => 233],
    ['name' => 'Salto', 'country_id' => 233],
    ['name' => 'San Jose', 'country_id' => 233],
    ['name' => 'Soriano', 'country_id' => 233],
    ['name' => 'Tacuarembo', 'country_id' => 233],
    ['name' => 'Treinta y Tres', 'country_id' => 233],
];