<?php return [
    ['name' => 'Amazonas', 'country_id' => 237],
    ['name' => 'Anzoategui', 'country_id' => 237],
    ['name' => 'Apure', 'country_id' => 237],
    ['name' => 'Aragua', 'country_id' => 237],
    ['name' => 'Barinas', 'country_id' => 237],
    ['name' => 'Bolivar', 'country_id' => 237],
    ['name' => 'Carabobo', 'country_id' => 237],
    ['name' => 'Cojedes', 'country_id' => 237],
    ['name' => 'Delta Amacuro', 'country_id' => 237],
    ['name' => 'Distrito Federal', 'country_id' => 237],
    ['name' => 'Falcon', 'country_id' => 237],
    ['name' => 'Guarico', 'country_id' => 237],
    ['name' => 'Lara', 'country_id' => 237],
    ['name' => 'Merida', 'country_id' => 237],
    ['name' => 'Miranda', 'country_id' => 237],
    ['name' => 'Monagas', 'country_id' => 237],
    ['name' => 'Nueva Esparta', 'country_id' => 237],
    ['name' => 'Portuguesa', 'country_id' => 237],
    ['name' => 'Sucre', 'country_id' => 237],
    ['name' => 'Tachira', 'country_id' => 237],
    ['name' => 'Trujillo', 'country_id' => 237],
    ['name' => 'Vargas', 'country_id' => 237],
    ['name' => 'Yaracuy', 'country_id' => 237],
    ['name' => 'Zulia', 'country_id' => 237],
];