<?php return [
    ['name' => 'Bac Giang', 'country_id' => 238],
    ['name' => 'Binh Dinh', 'country_id' => 238],
    ['name' => 'Binh Duong', 'country_id' => 238],
    ['name' => 'Da Nang', 'country_id' => 238],
    ['name' => 'Dong Bang Song Cuu Long', 'country_id' => 238],
    ['name' => 'Dong Bang Song Hong', 'country_id' => 238],
    ['name' => 'Dong Nai', 'country_id' => 238],
    ['name' => 'Dong Nam Bo', 'country_id' => 238],
    ['name' => 'Duyen Hai Mien Trung', 'country_id' => 238],
    ['name' => 'Hanoi', 'country_id' => 238],
    ['name' => 'Hung Yen', 'country_id' => 238],
    ['name' => 'Khu Bon Cu', 'country_id' => 238],
    ['name' => 'Long An', 'country_id' => 238],
    ['name' => 'Mien Nui Va Trung Du', 'country_id' => 238],
    ['name' => 'Thai Nguyen', 'country_id' => 238],
    ['name' => 'Thanh Pho Ho Chi Minh', 'country_id' => 238],
    ['name' => 'Thu Do Ha Noi', 'country_id' => 238],
    ['name' => 'Tinh Can Tho', 'country_id' => 238],
    ['name' => 'Tinh Da Nang', 'country_id' => 238],
    ['name' => 'Tinh Gia Lai', 'country_id' => 238],
];