<?php return [
    ['name' => '\'Adan', 'country_id' => 243],
    ['name' => 'Abyan', 'country_id' => 243],
    ['name' => 'Dhamar', 'country_id' => 243],
    ['name' => 'Hadramaut', 'country_id' => 243],
    ['name' => 'Hajjah', 'country_id' => 243],
    ['name' => 'Hudaydah', 'country_id' => 243],
    ['name' => 'Ibb', 'country_id' => 243],
    ['name' => 'Lahij', 'country_id' => 243],
    ['name' => 'Ma\'rib', 'country_id' => 243],
    ['name' => 'Madinat San\'a', 'country_id' => 243],
    ['name' => 'Sa\'dah', 'country_id' => 243],
    ['name' => 'Sana', 'country_id' => 243],
    ['name' => 'Shabwah', 'country_id' => 243],
    ['name' => 'Ta\'izz', 'country_id' => 243],
    ['name' => 'al-Bayda', 'country_id' => 243],
    ['name' => 'al-Hudaydah', 'country_id' => 243],
    ['name' => 'al-Jawf', 'country_id' => 243],
    ['name' => 'al-Mahrah', 'country_id' => 243],
    ['name' => 'al-Mahwit', 'country_id' => 243],
];