<?php return [
    ['name' => 'Bumthang', 'country_id' => 25],
    ['name' => 'Chhukha', 'country_id' => 25],
    ['name' => 'Chirang', 'country_id' => 25],
    ['name' => 'Daga', 'country_id' => 25],
    ['name' => 'Geylegphug', 'country_id' => 25],
    ['name' => 'Ha', 'country_id' => 25],
    ['name' => 'Lhuntshi', 'country_id' => 25],
    ['name' => 'Mongar', 'country_id' => 25],
    ['name' => 'Pemagatsel', 'country_id' => 25],
    ['name' => 'Punakha', 'country_id' => 25],
    ['name' => 'Rinpung', 'country_id' => 25],
    ['name' => 'Samchi', 'country_id' => 25],
    ['name' => 'Samdrup Jongkhar', 'country_id' => 25],
    ['name' => 'Shemgang', 'country_id' => 25],
    ['name' => 'Tashigang', 'country_id' => 25],
    ['name' => 'Timphu', 'country_id' => 25],
    ['name' => 'Tongsa', 'country_id' => 25],
    ['name' => 'Wangdiphodrang', 'country_id' => 25],
];