<?php return [
    ['name' => 'Central Bobonong', 'country_id' => 28],
    ['name' => 'Central Boteti', 'country_id' => 28],
    ['name' => 'Central Mahalapye', 'country_id' => 28],
    ['name' => 'Central Serowe-Palapye', 'country_id' => 28],
    ['name' => 'Central Tutume', 'country_id' => 28],
    ['name' => 'Chobe', 'country_id' => 28],
    ['name' => 'Francistown', 'country_id' => 28],
    ['name' => 'Gaborone', 'country_id' => 28],
    ['name' => 'Ghanzi', 'country_id' => 28],
    ['name' => 'Jwaneng', 'country_id' => 28],
    ['name' => 'Kgalagadi North', 'country_id' => 28],
    ['name' => 'Kgalagadi South', 'country_id' => 28],
    ['name' => 'Kgatleng', 'country_id' => 28],
    ['name' => 'Kweneng', 'country_id' => 28],
    ['name' => 'Lobatse', 'country_id' => 28],
    ['name' => 'Ngamiland', 'country_id' => 28],
    ['name' => 'Ngwaketse', 'country_id' => 28],
    ['name' => 'North East', 'country_id' => 28],
    ['name' => 'Okavango', 'country_id' => 28],
    ['name' => 'Orapa', 'country_id' => 28],
    ['name' => 'Selibe Phikwe', 'country_id' => 28],
    ['name' => 'South East', 'country_id' => 28],
    ['name' => 'Sowa', 'country_id' => 28],
];