<?php return [
    ['name' => '\'Ayn Daflah', 'country_id' => 3],
    ['name' => '\'Ayn Tamushanat', 'country_id' => 3],
    ['name' => 'Adrar', 'country_id' => 3],
    ['name' => 'Algiers', 'country_id' => 3],
    ['name' => 'Annabah', 'country_id' => 3],
    ['name' => 'Bashshar', 'country_id' => 3],
    ['name' => 'Batnah', 'country_id' => 3],
    ['name' => 'Bijayah', 'country_id' => 3],
    ['name' => 'Biskrah', 'country_id' => 3],
    ['name' => 'Blidah', 'country_id' => 3],
    ['name' => 'Buirah', 'country_id' => 3],
    ['name' => 'Bumardas', 'country_id' => 3],
    ['name' => 'Burj Bu Arririj', 'country_id' => 3],
    ['name' => 'Ghalizan', 'country_id' => 3],
    ['name' => 'Ghardayah', 'country_id' => 3],
    ['name' => 'Ilizi', 'country_id' => 3],
    ['name' => 'Jijili', 'country_id' => 3],
    ['name' => 'Jilfah', 'country_id' => 3],
    ['name' => 'Khanshalah', 'country_id' => 3],
    ['name' => 'Masilah', 'country_id' => 3],
    ['name' => 'Midyah', 'country_id' => 3],
    ['name' => 'Milah', 'country_id' => 3],
    ['name' => 'Muaskar', 'country_id' => 3],
    ['name' => 'Mustaghanam', 'country_id' => 3],
    ['name' => 'Naama', 'country_id' => 3],
    ['name' => 'Oran', 'country_id' => 3],
    ['name' => 'Ouargla', 'country_id' => 3],
    ['name' => 'Qalmah', 'country_id' => 3],
    ['name' => 'Qustantinah', 'country_id' => 3],
    ['name' => 'Sakikdah', 'country_id' => 3],
    ['name' => 'Satif', 'country_id' => 3],
    ['name' => 'Sayda\'', 'country_id' => 3],
    ['name' => 'Sidi ban-al-\'Abbas', 'country_id' => 3],
    ['name' => 'Suq Ahras', 'country_id' => 3],
    ['name' => 'Tamanghasat', 'country_id' => 3],
    ['name' => 'Tibazah', 'country_id' => 3],
    ['name' => 'Tibissah', 'country_id' => 3],
    ['name' => 'Tilimsan', 'country_id' => 3],
    ['name' => 'Tinduf', 'country_id' => 3],
    ['name' => 'Tisamsilt', 'country_id' => 3],
    ['name' => 'Tiyarat', 'country_id' => 3],
    ['name' => 'Tizi Wazu', 'country_id' => 3],
    ['name' => 'Umm-al-Bawaghi', 'country_id' => 3],
    ['name' => 'Wahran', 'country_id' => 3],
    ['name' => 'Warqla', 'country_id' => 3],
    ['name' => 'Wilaya d Alger', 'country_id' => 3],
    ['name' => 'Wilaya de Bejaia', 'country_id' => 3],
    ['name' => 'Wilaya de Constantine', 'country_id' => 3],
    ['name' => 'al-Aghwat', 'country_id' => 3],
    ['name' => 'al-Bayadh', 'country_id' => 3],
    ['name' => 'al-Jaza\'ir', 'country_id' => 3],
    ['name' => 'al-Wad', 'country_id' => 3],
    ['name' => 'ash-Shalif', 'country_id' => 3],
    ['name' => 'at-Tarif', 'country_id' => 3],
];