<?php return [
    ['name' => 'Acre', 'country_id' => 30],
    ['name' => 'Alagoas', 'country_id' => 30],
    ['name' => 'Amapa', 'country_id' => 30],
    ['name' => 'Amazonas', 'country_id' => 30],
    ['name' => 'Bahia', 'country_id' => 30],
    ['name' => 'Ceara', 'country_id' => 30],
    ['name' => 'Distrito Federal', 'country_id' => 30],
    ['name' => 'Espirito Santo', 'country_id' => 30],
    ['name' => 'Estado de Sao Paulo', 'country_id' => 30],
    ['name' => 'Goias', 'country_id' => 30],
    ['name' => 'Maranhao', 'country_id' => 30],
    ['name' => 'Mato Grosso', 'country_id' => 30],
    ['name' => 'Mato Grosso do Sul', 'country_id' => 30],
    ['name' => 'Minas Gerais', 'country_id' => 30],
    ['name' => 'Para', 'country_id' => 30],
    ['name' => 'Paraiba', 'country_id' => 30],
    ['name' => 'Parana', 'country_id' => 30],
    ['name' => 'Pernambuco', 'country_id' => 30],
    ['name' => 'Piaui', 'country_id' => 30],
    ['name' => 'Rio Grande do Norte', 'country_id' => 30],
    ['name' => 'Rio Grande do Sul', 'country_id' => 30],
    ['name' => 'Rio de Janeiro', 'country_id' => 30],
    ['name' => 'Rondonia', 'country_id' => 30],
    ['name' => 'Roraima', 'country_id' => 30],
    ['name' => 'Santa Catarina', 'country_id' => 30],
    ['name' => 'Sao Paulo', 'country_id' => 30],
    ['name' => 'Sergipe', 'country_id' => 30],
    ['name' => 'Tocantins', 'country_id' => 30],
];