<?php return [
    ['name' => 'Blagoevgrad', 'country_id' => 33],
    ['name' => 'Burgas', 'country_id' => 33],
    ['name' => 'Dobrich', 'country_id' => 33],
    ['name' => 'Gabrovo', 'country_id' => 33],
    ['name' => 'Haskovo', 'country_id' => 33],
    ['name' => 'Jambol', 'country_id' => 33],
    ['name' => 'Kardzhali', 'country_id' => 33],
    ['name' => 'Kjustendil', 'country_id' => 33],
    ['name' => 'Lovech', 'country_id' => 33],
    ['name' => 'Montana', 'country_id' => 33],
    ['name' => 'Oblast Sofiya-Grad', 'country_id' => 33],
    ['name' => 'Pazardzhik', 'country_id' => 33],
    ['name' => 'Pernik', 'country_id' => 33],
    ['name' => 'Pleven', 'country_id' => 33],
    ['name' => 'Plovdiv', 'country_id' => 33],
    ['name' => 'Razgrad', 'country_id' => 33],
    ['name' => 'Ruse', 'country_id' => 33],
    ['name' => 'Shumen', 'country_id' => 33],
    ['name' => 'Silistra', 'country_id' => 33],
    ['name' => 'Sliven', 'country_id' => 33],
    ['name' => 'Smoljan', 'country_id' => 33],
    ['name' => 'Sofija grad', 'country_id' => 33],
    ['name' => 'Sofijska oblast', 'country_id' => 33],
    ['name' => 'Stara Zagora', 'country_id' => 33],
    ['name' => 'Targovishte', 'country_id' => 33],
    ['name' => 'Varna', 'country_id' => 33],
    ['name' => 'Veliko Tarnovo', 'country_id' => 33],
    ['name' => 'Vidin', 'country_id' => 33],
    ['name' => 'Vraca', 'country_id' => 33],
    ['name' => 'Yablaniza', 'country_id' => 33],
];