<?php return [
    ['name' => 'Bubanza', 'country_id' => 35],
    ['name' => 'Bujumbura', 'country_id' => 35],
    ['name' => 'Bururi', 'country_id' => 35],
    ['name' => 'Cankuzo', 'country_id' => 35],
    ['name' => 'Cibitoke', 'country_id' => 35],
    ['name' => 'Gitega', 'country_id' => 35],
    ['name' => 'Karuzi', 'country_id' => 35],
    ['name' => 'Kayanza', 'country_id' => 35],
    ['name' => 'Kirundo', 'country_id' => 35],
    ['name' => 'Makamba', 'country_id' => 35],
    ['name' => 'Muramvya', 'country_id' => 35],
    ['name' => 'Muyinga', 'country_id' => 35],
    ['name' => 'Ngozi', 'country_id' => 35],
    ['name' => 'Rutana', 'country_id' => 35],
    ['name' => 'Ruyigi', 'country_id' => 35],
];