<?php return [
    ['name' => 'Banteay Mean Chey', 'country_id' => 36],
    ['name' => 'Bat Dambang', 'country_id' => 36],
    ['name' => 'Kampong Cham', 'country_id' => 36],
    ['name' => 'Kampong Chhnang', 'country_id' => 36],
    ['name' => 'Kampong Spoeu', 'country_id' => 36],
    ['name' => 'Kampong Thum', 'country_id' => 36],
    ['name' => 'Kampot', 'country_id' => 36],
    ['name' => 'Kandal', 'country_id' => 36],
    ['name' => 'Kaoh Kong', 'country_id' => 36],
    ['name' => 'Kracheh', 'country_id' => 36],
    ['name' => 'Krong Kaeb', 'country_id' => 36],
    ['name' => 'Krong Pailin', 'country_id' => 36],
    ['name' => 'Krong Preah Sihanouk', 'country_id' => 36],
    ['name' => 'Mondol Kiri', 'country_id' => 36],
    ['name' => 'Otdar Mean Chey', 'country_id' => 36],
    ['name' => 'Phnum Penh', 'country_id' => 36],
    ['name' => 'Pousat', 'country_id' => 36],
    ['name' => 'Preah Vihear', 'country_id' => 36],
    ['name' => 'Prey Veaeng', 'country_id' => 36],
    ['name' => 'Rotanak Kiri', 'country_id' => 36],
    ['name' => 'Siem Reab', 'country_id' => 36],
    ['name' => 'Stueng Traeng', 'country_id' => 36],
    ['name' => 'Svay Rieng', 'country_id' => 36],
    ['name' => 'Takaev', 'country_id' => 36],
];