<?php return [
    ['name' => 'Bamingui-Bangoran', 'country_id' => 41],
    ['name' => 'Bangui', 'country_id' => 41],
    ['name' => 'Basse-Kotto', 'country_id' => 41],
    ['name' => 'Haut-Mbomou', 'country_id' => 41],
    ['name' => 'Haute-Kotto', 'country_id' => 41],
    ['name' => 'Kemo', 'country_id' => 41],
    ['name' => 'Lobaye', 'country_id' => 41],
    ['name' => 'Mambere-Kadei', 'country_id' => 41],
    ['name' => 'Mbomou', 'country_id' => 41],
    ['name' => 'Nana-Gribizi', 'country_id' => 41],
    ['name' => 'Nana-Mambere', 'country_id' => 41],
    ['name' => 'Ombella Mpoko', 'country_id' => 41],
    ['name' => 'Ouaka', 'country_id' => 41],
    ['name' => 'Ouham', 'country_id' => 41],
    ['name' => 'Ouham-Pende', 'country_id' => 41],
    ['name' => 'Sangha-Mbaere', 'country_id' => 41],
    ['name' => 'Vakaga', 'country_id' => 41],
];