<?php return [
    ['name' => 'Aisen', 'country_id' => 43],
    ['name' => 'Antofagasta', 'country_id' => 43],
    ['name' => 'Araucania', 'country_id' => 43],
    ['name' => 'Atacama', 'country_id' => 43],
    ['name' => 'Bio Bio', 'country_id' => 43],
    ['name' => 'Coquimbo', 'country_id' => 43],
    ['name' => 'Libertador General Bernardo O\'', 'country_id' => 43],
    ['name' => 'Los Lagos', 'country_id' => 43],
    ['name' => 'Magellanes', 'country_id' => 43],
    ['name' => 'Maule', 'country_id' => 43],
    ['name' => 'Metropolitana', 'country_id' => 43],
    ['name' => 'Metropolitana de Santiago', 'country_id' => 43],
    ['name' => 'Tarapaca', 'country_id' => 43],
    ['name' => 'Valparaiso', 'country_id' => 43],
];