<?php return [
    ['name' => 'Anhui', 'country_id' => 44],
    ['name' => 'Anhui Province', 'country_id' => 44],
    ['name' => 'Anhui Sheng', 'country_id' => 44],
    ['name' => 'Aomen', 'country_id' => 44],
    ['name' => 'Beijing', 'country_id' => 44],
    ['name' => 'Beijing Shi', 'country_id' => 44],
    ['name' => 'Chongqing', 'country_id' => 44],
    ['name' => 'Fujian', 'country_id' => 44],
    ['name' => 'Fujian Sheng', 'country_id' => 44],
    ['name' => 'Gansu', 'country_id' => 44],
    ['name' => 'Guangdong', 'country_id' => 44],
    ['name' => 'Guangdong Sheng', 'country_id' => 44],
    ['name' => 'Guangxi', 'country_id' => 44],
    ['name' => 'Guizhou', 'country_id' => 44],
    ['name' => 'Hainan', 'country_id' => 44],
    ['name' => 'Hebei', 'country_id' => 44],
    ['name' => 'Heilongjiang', 'country_id' => 44],
    ['name' => 'Henan', 'country_id' => 44],
    ['name' => 'Hubei', 'country_id' => 44],
    ['name' => 'Hunan', 'country_id' => 44],
    ['name' => 'Jiangsu', 'country_id' => 44],
    ['name' => 'Jiangsu Sheng', 'country_id' => 44],
    ['name' => 'Jiangxi', 'country_id' => 44],
    ['name' => 'Jilin', 'country_id' => 44],
    ['name' => 'Liaoning', 'country_id' => 44],
    ['name' => 'Liaoning Sheng', 'country_id' => 44],
    ['name' => 'Nei Monggol', 'country_id' => 44],
    ['name' => 'Ningxia Hui', 'country_id' => 44],
    ['name' => 'Qinghai', 'country_id' => 44],
    ['name' => 'Shaanxi', 'country_id' => 44],
    ['name' => 'Shandong', 'country_id' => 44],
    ['name' => 'Shandong Sheng', 'country_id' => 44],
    ['name' => 'Shanghai', 'country_id' => 44],
    ['name' => 'Shanxi', 'country_id' => 44],
    ['name' => 'Sichuan', 'country_id' => 44],
    ['name' => 'Tianjin', 'country_id' => 44],
    ['name' => 'Xianggang', 'country_id' => 44],
    ['name' => 'Xinjiang', 'country_id' => 44],
    ['name' => 'Xizang', 'country_id' => 44],
    ['name' => 'Yunnan', 'country_id' => 44],
    ['name' => 'Zhejiang', 'country_id' => 44],
    ['name' => 'Zhejiang Sheng', 'country_id' => 44],
];