<?php return [
    ['name' => 'Amazonas', 'country_id' => 47],
    ['name' => 'Antioquia', 'country_id' => 47],
    ['name' => 'Arauca', 'country_id' => 47],
    ['name' => 'Atlantico', 'country_id' => 47],
    ['name' => 'Bogota', 'country_id' => 47],
    ['name' => 'Bolivar', 'country_id' => 47],
    ['name' => 'Boyaca', 'country_id' => 47],
    ['name' => 'Caldas', 'country_id' => 47],
    ['name' => 'Caqueta', 'country_id' => 47],
    ['name' => 'Casanare', 'country_id' => 47],
    ['name' => 'Cauca', 'country_id' => 47],
    ['name' => 'Cesar', 'country_id' => 47],
    ['name' => 'Choco', 'country_id' => 47],
    ['name' => 'Cordoba', 'country_id' => 47],
    ['name' => 'Cundinamarca', 'country_id' => 47],
    ['name' => 'Guainia', 'country_id' => 47],
    ['name' => 'Guaviare', 'country_id' => 47],
    ['name' => 'Huila', 'country_id' => 47],
    ['name' => 'La Guajira', 'country_id' => 47],
    ['name' => 'Magdalena', 'country_id' => 47],
    ['name' => 'Meta', 'country_id' => 47],
    ['name' => 'Narino', 'country_id' => 47],
    ['name' => 'Norte de Santander', 'country_id' => 47],
    ['name' => 'Putumayo', 'country_id' => 47],
    ['name' => 'Quindio', 'country_id' => 47],
    ['name' => 'Risaralda', 'country_id' => 47],
    ['name' => 'San Andres y Providencia', 'country_id' => 47],
    ['name' => 'Santander', 'country_id' => 47],
    ['name' => 'Sucre', 'country_id' => 47],
    ['name' => 'Tolima', 'country_id' => 47],
    ['name' => 'Valle del Cauca', 'country_id' => 47],
    ['name' => 'Vaupes', 'country_id' => 47],
    ['name' => 'Vichada', 'country_id' => 47],
];