<?php return [
    ['name' => 'Bas-Uele', 'country_id' => 50],
    ['name' => 'Equateur', 'country_id' => 50],
    ['name' => 'Haut-Katanga', 'country_id' => 50],
    ['name' => 'Haut-Lomami', 'country_id' => 50],
    ['name' => 'Haut-Uele', 'country_id' => 50],
    ['name' => 'Ituri', 'country_id' => 50],
    ['name' => 'Kasai', 'country_id' => 50],
    ['name' => 'Kasai Central', 'country_id' => 50],
    ['name' => 'Kasai Oriental', 'country_id' => 50],
    ['name' => 'Kinshasa', 'country_id' => 50],
    ['name' => 'Kongo-Central', 'country_id' => 50],
    ['name' => 'Kwango', 'country_id' => 50],
    ['name' => 'Kwilu', 'country_id' => 50],
    ['name' => 'Lomami', 'country_id' => 50],
    ['name' => 'Lualaba', 'country_id' => 50],
    ['name' => 'Mai-Ndombe', 'country_id' => 50],
    ['name' => 'Maniema', 'country_id' => 50],
    ['name' => 'Mongola', 'country_id' => 50],
    ['name' => 'Nord-Kivu', 'country_id' => 50],
    ['name' => 'Nord-Ubangi', 'country_id' => 50],
    ['name' => 'Sankuru', 'country_id' => 50],
    ['name' => 'Sud-Kivu', 'country_id' => 50],
    ['name' => 'Sub-Ubangi', 'country_id' => 50],
    ['name' => 'Tanganyika', 'country_id' => 50],
    ['name' => 'Tshopo', 'country_id' => 50],
    ['name' => 'Tshuapa', 'country_id' => 50],
];