<?php return [
    ['name' => 'Abidjan', 'country_id' => 53],
    ['name' => 'Agneby', 'country_id' => 53],
    ['name' => 'Bafing', 'country_id' => 53],
    ['name' => 'Denguele', 'country_id' => 53],
    ['name' => 'Dix-huit Montagnes', 'country_id' => 53],
    ['name' => 'Fromager', 'country_id' => 53],
    ['name' => 'Haut-Sassandra', 'country_id' => 53],
    ['name' => 'Lacs', 'country_id' => 53],
    ['name' => 'Lagunes', 'country_id' => 53],
    ['name' => 'Marahoue', 'country_id' => 53],
    ['name' => 'Moyen-Cavally', 'country_id' => 53],
    ['name' => 'Moyen-Comoe', 'country_id' => 53],
    ['name' => 'N\'zi-Comoe', 'country_id' => 53],
    ['name' => 'Sassandra', 'country_id' => 53],
    ['name' => 'Savanes', 'country_id' => 53],
    ['name' => 'Sud-Bandama', 'country_id' => 53],
    ['name' => 'Sud-Comoe', 'country_id' => 53],
    ['name' => 'Vallee du Bandama', 'country_id' => 53],
    ['name' => 'Worodougou', 'country_id' => 53],
    ['name' => 'Zanzan', 'country_id' => 53],
];