<?php return [
    ['name' => 'Bjelovar-Bilogora', 'country_id' => 54],
    ['name' => 'Dubrovnik-Neretva', 'country_id' => 54],
    ['name' => 'Grad Zagreb', 'country_id' => 54],
    ['name' => 'Istra', 'country_id' => 54],
    ['name' => 'Karlovac', 'country_id' => 54],
    ['name' => 'Koprivnica-Krizhevci', 'country_id' => 54],
    ['name' => 'Krapina-Zagorje', 'country_id' => 54],
    ['name' => 'Lika-Senj', 'country_id' => 54],
    ['name' => 'Medhimurje', 'country_id' => 54],
    ['name' => 'Medimurska Zupanija', 'country_id' => 54],
    ['name' => 'Osijek-Baranja', 'country_id' => 54],
    ['name' => 'Osjecko-Baranjska Zupanija', 'country_id' => 54],
    ['name' => 'Pozhega-Slavonija', 'country_id' => 54],
    ['name' => 'Primorje-Gorski Kotar', 'country_id' => 54],
    ['name' => 'Shibenik-Knin', 'country_id' => 54],
    ['name' => 'Sisak-Moslavina', 'country_id' => 54],
    ['name' => 'Slavonski Brod-Posavina', 'country_id' => 54],
    ['name' => 'Split-Dalmacija', 'country_id' => 54],
    ['name' => 'Varazhdin', 'country_id' => 54],
    ['name' => 'Virovitica-Podravina', 'country_id' => 54],
    ['name' => 'Vukovar-Srijem', 'country_id' => 54],
    ['name' => 'Zadar', 'country_id' => 54],
    ['name' => 'Zagreb', 'country_id' => 54],
];