<?php return [
    ['name' => 'Central Bohemian', 'country_id' => 57],
    ['name' => 'Frycovice', 'country_id' => 57],
    ['name' => 'Jihocesky Kraj', 'country_id' => 57],
    ['name' => 'Jihochesky', 'country_id' => 57],
    ['name' => 'Jihomoravsky', 'country_id' => 57],
    ['name' => 'Karlovarsky', 'country_id' => 57],
    ['name' => 'Klecany', 'country_id' => 57],
    ['name' => 'Kralovehradecky', 'country_id' => 57],
    ['name' => 'Liberecky', 'country_id' => 57],
    ['name' => 'Lipov', 'country_id' => 57],
    ['name' => 'Moravskoslezsky', 'country_id' => 57],
    ['name' => 'Olomoucky', 'country_id' => 57],
    ['name' => 'Olomoucky Kraj', 'country_id' => 57],
    ['name' => 'Pardubicky', 'country_id' => 57],
    ['name' => 'Plzensky', 'country_id' => 57],
    ['name' => 'Praha', 'country_id' => 57],
    ['name' => 'Rajhrad', 'country_id' => 57],
    ['name' => 'Smirice', 'country_id' => 57],
    ['name' => 'South Moravian', 'country_id' => 57],
    ['name' => 'Straz nad Nisou', 'country_id' => 57],
    ['name' => 'Stredochesky', 'country_id' => 57],
    ['name' => 'Unicov', 'country_id' => 57],
    ['name' => 'Ustecky', 'country_id' => 57],
    ['name' => 'Valletta', 'country_id' => 57],
    ['name' => 'Velesin', 'country_id' => 57],
    ['name' => 'Vysochina', 'country_id' => 57],
    ['name' => 'Zlinsky', 'country_id' => 57],
];