<?php return [
    ['name' => 'Arhus', 'country_id' => 58],
    ['name' => 'Bornholm', 'country_id' => 58],
    ['name' => 'Frederiksborg', 'country_id' => 58],
    ['name' => 'Fyn', 'country_id' => 58],
    ['name' => 'Hovedstaden', 'country_id' => 58],
    ['name' => 'Kobenhavn', 'country_id' => 58],
    ['name' => 'Kobenhavns Amt', 'country_id' => 58],
    ['name' => 'Kobenhavns Kommune', 'country_id' => 58],
    ['name' => 'Nordjylland', 'country_id' => 58],
    ['name' => 'Ribe', 'country_id' => 58],
    ['name' => 'Ringkobing', 'country_id' => 58],
    ['name' => 'Roervig', 'country_id' => 58],
    ['name' => 'Roskilde', 'country_id' => 58],
    ['name' => 'Roslev', 'country_id' => 58],
    ['name' => 'Sjaelland', 'country_id' => 58],
    ['name' => 'Soeborg', 'country_id' => 58],
    ['name' => 'Sonderjylland', 'country_id' => 58],
    ['name' => 'Storstrom', 'country_id' => 58],
    ['name' => 'Syddanmark', 'country_id' => 58],
    ['name' => 'Toelloese', 'country_id' => 58],
    ['name' => 'Vejle', 'country_id' => 58],
    ['name' => 'Vestsjalland', 'country_id' => 58],
    ['name' => 'Viborg', 'country_id' => 58],
];