<?php return [
    ['name' => 'Bengo', 'country_id' => 6],
    ['name' => 'Benguela', 'country_id' => 6],
    ['name' => 'Bie', 'country_id' => 6],
    ['name' => 'Cabinda', 'country_id' => 6],
    ['name' => 'Cunene', 'country_id' => 6],
    ['name' => 'Huambo', 'country_id' => 6],
    ['name' => 'Huila', 'country_id' => 6],
    ['name' => 'Kuando-Kubango', 'country_id' => 6],
    ['name' => 'Kwanza Norte', 'country_id' => 6],
    ['name' => 'Kwanza Sul', 'country_id' => 6],
    ['name' => 'Luanda', 'country_id' => 6],
    ['name' => 'Lunda Norte', 'country_id' => 6],
    ['name' => 'Lunda Sul', 'country_id' => 6],
    ['name' => 'Malanje', 'country_id' => 6],
    ['name' => 'Moxico', 'country_id' => 6],
    ['name' => 'Namibe', 'country_id' => 6],
    ['name' => 'Uige', 'country_id' => 6],
    ['name' => 'Zaire', 'country_id' => 6],
];