<?php return [
    ['name' => 'Azua', 'country_id' => 61],
    ['name' => 'Bahoruco', 'country_id' => 61],
    ['name' => 'Barahona', 'country_id' => 61],
    ['name' => 'Dajabon', 'country_id' => 61],
    ['name' => 'Distrito Nacional', 'country_id' => 61],
    ['name' => 'Duarte', 'country_id' => 61],
    ['name' => 'El Seybo', 'country_id' => 61],
    ['name' => 'Elias Pina', 'country_id' => 61],
    ['name' => 'Espaillat', 'country_id' => 61],
    ['name' => 'Hato Mayor', 'country_id' => 61],
    ['name' => 'Independencia', 'country_id' => 61],
    ['name' => 'La Altagracia', 'country_id' => 61],
    ['name' => 'La Romana', 'country_id' => 61],
    ['name' => 'La Vega', 'country_id' => 61],
    ['name' => 'Maria Trinidad Sanchez', 'country_id' => 61],
    ['name' => 'Monsenor Nouel', 'country_id' => 61],
    ['name' => 'Monte Cristi', 'country_id' => 61],
    ['name' => 'Monte Plata', 'country_id' => 61],
    ['name' => 'Pedernales', 'country_id' => 61],
    ['name' => 'Peravia', 'country_id' => 61],
    ['name' => 'Puerto Plata', 'country_id' => 61],
    ['name' => 'Salcedo', 'country_id' => 61],
    ['name' => 'Samana', 'country_id' => 61],
    ['name' => 'San Cristobal', 'country_id' => 61],
    ['name' => 'San Juan', 'country_id' => 61],
    ['name' => 'San Pedro de Macoris', 'country_id' => 61],
    ['name' => 'Sanchez Ramirez', 'country_id' => 61],
    ['name' => 'Santiago', 'country_id' => 61],
    ['name' => 'Santiago Rodriguez', 'country_id' => 61],
    ['name' => 'Valverde', 'country_id' => 61],
];