<?php return [
    ['name' => 'Azuay', 'country_id' => 63],
    ['name' => 'Bolivar', 'country_id' => 63],
    ['name' => 'Canar', 'country_id' => 63],
    ['name' => 'Carchi', 'country_id' => 63],
    ['name' => 'Chimborazo', 'country_id' => 63],
    ['name' => 'Cotopaxi', 'country_id' => 63],
    ['name' => 'El Oro', 'country_id' => 63],
    ['name' => 'Esmeraldas', 'country_id' => 63],
    ['name' => 'Galapagos', 'country_id' => 63],
    ['name' => 'Guayas', 'country_id' => 63],
    ['name' => 'Imbabura', 'country_id' => 63],
    ['name' => 'Loja', 'country_id' => 63],
    ['name' => 'Los Rios', 'country_id' => 63],
    ['name' => 'Manabi', 'country_id' => 63],
    ['name' => 'Morona Santiago', 'country_id' => 63],
    ['name' => 'Napo', 'country_id' => 63],
    ['name' => 'Orellana', 'country_id' => 63],
    ['name' => 'Pastaza', 'country_id' => 63],
    ['name' => 'Pichincha', 'country_id' => 63],
    ['name' => 'Sucumbios', 'country_id' => 63],
    ['name' => 'Tungurahua', 'country_id' => 63],
    ['name' => 'Zamora Chinchipe', 'country_id' => 63],
];