<?php return [
    ['name' => 'Aswan', 'country_id' => 64],
    ['name' => 'Asyut', 'country_id' => 64],
    ['name' => 'Bani Suwayf', 'country_id' => 64],
    ['name' => 'Bur Sa\'id', 'country_id' => 64],
    ['name' => 'Cairo', 'country_id' => 64],
    ['name' => 'Dumyat', 'country_id' => 64],
    ['name' => 'Kafr-ash-Shaykh', 'country_id' => 64],
    ['name' => 'Matruh', 'country_id' => 64],
    ['name' => 'Muhafazat ad Daqahliyah', 'country_id' => 64],
    ['name' => 'Muhafazat al Fayyum', 'country_id' => 64],
    ['name' => 'Muhafazat al Gharbiyah', 'country_id' => 64],
    ['name' => 'Muhafazat al Iskandariyah', 'country_id' => 64],
    ['name' => 'Muhafazat al Qahirah', 'country_id' => 64],
    ['name' => 'Qina', 'country_id' => 64],
    ['name' => 'Sawhaj', 'country_id' => 64],
    ['name' => 'Sina al-Janubiyah', 'country_id' => 64],
    ['name' => 'Sina ash-Shamaliyah', 'country_id' => 64],
    ['name' => 'ad-Daqahliyah', 'country_id' => 64],
    ['name' => 'al-Bahr-al-Ahmar', 'country_id' => 64],
    ['name' => 'al-Buhayrah', 'country_id' => 64],
    ['name' => 'al-Fayyum', 'country_id' => 64],
    ['name' => 'al-Gharbiyah', 'country_id' => 64],
    ['name' => 'al-Iskandariyah', 'country_id' => 64],
    ['name' => 'al-Ismailiyah', 'country_id' => 64],
    ['name' => 'al-Jizah', 'country_id' => 64],
    ['name' => 'al-Minufiyah', 'country_id' => 64],
    ['name' => 'al-Minya', 'country_id' => 64],
    ['name' => 'al-Qahira', 'country_id' => 64],
    ['name' => 'al-Qalyubiyah', 'country_id' => 64],
    ['name' => 'al-Uqsur', 'country_id' => 64],
    ['name' => 'al-Wadi al-Jadid', 'country_id' => 64],
    ['name' => 'as-Suways', 'country_id' => 64],
    ['name' => 'ash-Sharqiyah', 'country_id' => 64],
];