<?php return [
    ['name' => 'Ahuachapan', 'country_id' => 65],
    ['name' => 'Cabanas', 'country_id' => 65],
    ['name' => 'Chalatenango', 'country_id' => 65],
    ['name' => 'Cuscatlan', 'country_id' => 65],
    ['name' => 'La Libertad', 'country_id' => 65],
    ['name' => 'La Paz', 'country_id' => 65],
    ['name' => 'La Union', 'country_id' => 65],
    ['name' => 'Morazan', 'country_id' => 65],
    ['name' => 'San Miguel', 'country_id' => 65],
    ['name' => 'San Salvador', 'country_id' => 65],
    ['name' => 'San Vicente', 'country_id' => 65],
    ['name' => 'Santa Ana', 'country_id' => 65],
    ['name' => 'Sonsonate', 'country_id' => 65],
    ['name' => 'Usulutan', 'country_id' => 65],
];