<?php return [
    ['name' => 'Harju', 'country_id' => 68],
    ['name' => 'Hiiu', 'country_id' => 68],
    ['name' => 'Ida-Viru', 'country_id' => 68],
    ['name' => 'Jarva', 'country_id' => 68],
    ['name' => 'Jogeva', 'country_id' => 68],
    ['name' => 'Laane', 'country_id' => 68],
    ['name' => 'Laane-Viru', 'country_id' => 68],
    ['name' => 'Parnu', 'country_id' => 68],
    ['name' => 'Polva', 'country_id' => 68],
    ['name' => 'Rapla', 'country_id' => 68],
    ['name' => 'Saare', 'country_id' => 68],
    ['name' => 'Tartu', 'country_id' => 68],
    ['name' => 'Valga', 'country_id' => 68],
    ['name' => 'Viljandi', 'country_id' => 68],
    ['name' => 'Voru', 'country_id' => 68],
];