<?php return [
    ['name' => 'Ahvenanmaa', 'country_id' => 74],
    ['name' => 'Etela-Karjala', 'country_id' => 74],
    ['name' => 'Etela-Pohjanmaa', 'country_id' => 74],
    ['name' => 'Etela-Savo', 'country_id' => 74],
    ['name' => 'Etela-Suomen Laani', 'country_id' => 74],
    ['name' => 'Ita-Suomen Laani', 'country_id' => 74],
    ['name' => 'Ita-Uusimaa', 'country_id' => 74],
    ['name' => 'Kainuu', 'country_id' => 74],
    ['name' => 'Kanta-Hame', 'country_id' => 74],
    ['name' => 'Keski-Pohjanmaa', 'country_id' => 74],
    ['name' => 'Keski-Suomi', 'country_id' => 74],
    ['name' => 'Kymenlaakso', 'country_id' => 74],
    ['name' => 'Lansi-Suomen Laani', 'country_id' => 74],
    ['name' => 'Lappi', 'country_id' => 74],
    ['name' => 'Northern Savonia', 'country_id' => 74],
    ['name' => 'Ostrobothnia', 'country_id' => 74],
    ['name' => 'Oulun Laani', 'country_id' => 74],
    ['name' => 'Paijat-Hame', 'country_id' => 74],
    ['name' => 'Pirkanmaa', 'country_id' => 74],
    ['name' => 'Pohjanmaa', 'country_id' => 74],
    ['name' => 'Pohjois-Karjala', 'country_id' => 74],
    ['name' => 'Pohjois-Pohjanmaa', 'country_id' => 74],
    ['name' => 'Pohjois-Savo', 'country_id' => 74],
    ['name' => 'Saarijarvi', 'country_id' => 74],
    ['name' => 'Satakunta', 'country_id' => 74],
    ['name' => 'Southern Savonia', 'country_id' => 74],
    ['name' => 'Tavastia Proper', 'country_id' => 74],
    ['name' => 'Uleaborgs Lan', 'country_id' => 74],
    ['name' => 'Uusimaa', 'country_id' => 74],
    ['name' => 'Varsinais-Suomi', 'country_id' => 74],
];