<?php return [
    ['name' => 'Ain', 'country_id' => 75],
    ['name' => 'Aisne', 'country_id' => 75],
    ['name' => 'Albi Le Sequestre', 'country_id' => 75],
    ['name' => 'Allier', 'country_id' => 75],
    ['name' => 'Alpes-Cote dAzur', 'country_id' => 75],
    ['name' => 'Alpes-Maritimes', 'country_id' => 75],
    ['name' => 'Alpes-de-Haute-Provence', 'country_id' => 75],
    ['name' => 'Alsace', 'country_id' => 75],
    ['name' => 'Aquitaine', 'country_id' => 75],
    ['name' => 'Ardeche', 'country_id' => 75],
    ['name' => 'Ardennes', 'country_id' => 75],
    ['name' => 'Ariege', 'country_id' => 75],
    ['name' => 'Aube', 'country_id' => 75],
    ['name' => 'Aude', 'country_id' => 75],
    ['name' => 'Auvergne', 'country_id' => 75],
    ['name' => 'Aveyron', 'country_id' => 75],
    ['name' => 'Bas-Rhin', 'country_id' => 75],
    ['name' => 'Basse-Normandie', 'country_id' => 75],
    ['name' => 'Bouches-du-Rhone', 'country_id' => 75],
    ['name' => 'Bourgogne', 'country_id' => 75],
    ['name' => 'Bretagne', 'country_id' => 75],
    ['name' => 'Brittany', 'country_id' => 75],
    ['name' => 'Burgundy', 'country_id' => 75],
    ['name' => 'Calvados', 'country_id' => 75],
    ['name' => 'Cantal', 'country_id' => 75],
    ['name' => 'Cedex', 'country_id' => 75],
    ['name' => 'Centre', 'country_id' => 75],
    ['name' => 'Charente', 'country_id' => 75],
    ['name' => 'Charente-Maritime', 'country_id' => 75],
    ['name' => 'Cher', 'country_id' => 75],
    ['name' => 'Correze', 'country_id' => 75],
    ['name' => 'Corse-du-Sud', 'country_id' => 75],
    ['name' => 'Cote-d\'Or', 'country_id' => 75],
    ['name' => 'Cotes-d\'Armor', 'country_id' => 75],
    ['name' => 'Creuse', 'country_id' => 75],
    ['name' => 'Crolles', 'country_id' => 75],
    ['name' => 'Deux-Sevres', 'country_id' => 75],
    ['name' => 'Dordogne', 'country_id' => 75],
    ['name' => 'Doubs', 'country_id' => 75],
    ['name' => 'Drome', 'country_id' => 75],
    ['name' => 'Essonne', 'country_id' => 75],
    ['name' => 'Eure', 'country_id' => 75],
    ['name' => 'Eure-et-Loir', 'country_id' => 75],
    ['name' => 'Feucherolles', 'country_id' => 75],
    ['name' => 'Finistere', 'country_id' => 75],
    ['name' => 'Franche-Comte', 'country_id' => 75],
    ['name' => 'Gard', 'country_id' => 75],
    ['name' => 'Gers', 'country_id' => 75],
    ['name' => 'Gironde', 'country_id' => 75],
    ['name' => 'Haut-Rhin', 'country_id' => 75],
    ['name' => 'Haute-Corse', 'country_id' => 75],
    ['name' => 'Haute-Garonne', 'country_id' => 75],
    ['name' => 'Haute-Loire', 'country_id' => 75],
    ['name' => 'Haute-Marne', 'country_id' => 75],
    ['name' => 'Haute-Saone', 'country_id' => 75],
    ['name' => 'Haute-Savoie', 'country_id' => 75],
    ['name' => 'Haute-Vienne', 'country_id' => 75],
    ['name' => 'Hautes-Alpes', 'country_id' => 75],
    ['name' => 'Hautes-Pyrenees', 'country_id' => 75],
    ['name' => 'Hauts-de-Seine', 'country_id' => 75],
    ['name' => 'Herault', 'country_id' => 75],
    ['name' => 'Ile-de-France', 'country_id' => 75],
    ['name' => 'Ille-et-Vilaine', 'country_id' => 75],
    ['name' => 'Indre', 'country_id' => 75],
    ['name' => 'Indre-et-Loire', 'country_id' => 75],
    ['name' => 'Isere', 'country_id' => 75],
    ['name' => 'Jura', 'country_id' => 75],
    ['name' => 'Klagenfurt', 'country_id' => 75],
    ['name' => 'Landes', 'country_id' => 75],
    ['name' => 'Languedoc-Roussillon', 'country_id' => 75],
    ['name' => 'Larcay', 'country_id' => 75],
    ['name' => 'Le Castellet', 'country_id' => 75],
    ['name' => 'Le Creusot', 'country_id' => 75],
    ['name' => 'Limousin', 'country_id' => 75],
    ['name' => 'Loir-et-Cher', 'country_id' => 75],
    ['name' => 'Loire', 'country_id' => 75],
    ['name' => 'Loire-Atlantique', 'country_id' => 75],
    ['name' => 'Loiret', 'country_id' => 75],
    ['name' => 'Lorraine', 'country_id' => 75],
    ['name' => 'Lot', 'country_id' => 75],
    ['name' => 'Lot-et-Garonne', 'country_id' => 75],
    ['name' => 'Lower Normandy', 'country_id' => 75],
    ['name' => 'Lozere', 'country_id' => 75],
    ['name' => 'Maine-et-Loire', 'country_id' => 75],
    ['name' => 'Manche', 'country_id' => 75],
    ['name' => 'Marne', 'country_id' => 75],
    ['name' => 'Mayenne', 'country_id' => 75],
    ['name' => 'Meurthe-et-Moselle', 'country_id' => 75],
    ['name' => 'Meuse', 'country_id' => 75],
    ['name' => 'Midi-Pyrenees', 'country_id' => 75],
    ['name' => 'Morbihan', 'country_id' => 75],
    ['name' => 'Moselle', 'country_id' => 75],
    ['name' => 'Nievre', 'country_id' => 75],
    ['name' => 'Nord', 'country_id' => 75],
    ['name' => 'Nord-Pas-de-Calais', 'country_id' => 75],
    ['name' => 'Oise', 'country_id' => 75],
    ['name' => 'Orne', 'country_id' => 75],
    ['name' => 'Paris', 'country_id' => 75],
    ['name' => 'Pas-de-Calais', 'country_id' => 75],
    ['name' => 'Pays de la Loire', 'country_id' => 75],
    ['name' => 'Pays-de-la-Loire', 'country_id' => 75],
    ['name' => 'Picardy', 'country_id' => 75],
    ['name' => 'Puy-de-Dome', 'country_id' => 75],
    ['name' => 'Pyrenees-Atlantiques', 'country_id' => 75],
    ['name' => 'Pyrenees-Orientales', 'country_id' => 75],
    ['name' => 'Quelmes', 'country_id' => 75],
    ['name' => 'Rhone', 'country_id' => 75],
    ['name' => 'Rhone-Alpes', 'country_id' => 75],
    ['name' => 'Saint Ouen', 'country_id' => 75],
    ['name' => 'Saint Viatre', 'country_id' => 75],
    ['name' => 'Saone-et-Loire', 'country_id' => 75],
    ['name' => 'Sarthe', 'country_id' => 75],
    ['name' => 'Savoie', 'country_id' => 75],
    ['name' => 'Seine-Maritime', 'country_id' => 75],
    ['name' => 'Seine-Saint-Denis', 'country_id' => 75],
    ['name' => 'Seine-et-Marne', 'country_id' => 75],
    ['name' => 'Somme', 'country_id' => 75],
    ['name' => 'Sophia Antipolis', 'country_id' => 75],
    ['name' => 'Souvans', 'country_id' => 75],
    ['name' => 'Tarn', 'country_id' => 75],
    ['name' => 'Tarn-et-Garonne', 'country_id' => 75],
    ['name' => 'Territoire de Belfort', 'country_id' => 75],
    ['name' => 'Treignac', 'country_id' => 75],
    ['name' => 'Upper Normandy', 'country_id' => 75],
    ['name' => 'Val-d\'Oise', 'country_id' => 75],
    ['name' => 'Val-de-Marne', 'country_id' => 75],
    ['name' => 'Var', 'country_id' => 75],
    ['name' => 'Vaucluse', 'country_id' => 75],
    ['name' => 'Vellise', 'country_id' => 75],
    ['name' => 'Vendee', 'country_id' => 75],
    ['name' => 'Vienne', 'country_id' => 75],
    ['name' => 'Vosges', 'country_id' => 75],
    ['name' => 'Yonne', 'country_id' => 75],
    ['name' => 'Yvelines', 'country_id' => 75],
];