<?php return [
    ['name' => 'Auvergne', 'country_id' => 82],
    ['name' => 'Baden-Wurttemberg', 'country_id' => 82],
    ['name' => 'Bavaria', 'country_id' => 82],
    ['name' => 'Bayern', 'country_id' => 82],
    ['name' => 'Beilstein Wurtt', 'country_id' => 82],
    ['name' => 'Berlin', 'country_id' => 82],
    ['name' => 'Brandenburg', 'country_id' => 82],
    ['name' => 'Bremen', 'country_id' => 82],
    ['name' => 'Dreisbach', 'country_id' => 82],
    ['name' => 'Freistaat Bayern', 'country_id' => 82],
    ['name' => 'Hamburg', 'country_id' => 82],
    ['name' => 'Hannover', 'country_id' => 82],
    ['name' => 'Heroldstatt', 'country_id' => 82],
    ['name' => 'Hessen', 'country_id' => 82],
    ['name' => 'Kortenberg', 'country_id' => 82],
    ['name' => 'Laasdorf', 'country_id' => 82],
    ['name' => 'Land Baden-Wurttemberg', 'country_id' => 82],
    ['name' => 'Land Bayern', 'country_id' => 82],
    ['name' => 'Land Brandenburg', 'country_id' => 82],
    ['name' => 'Land Hessen', 'country_id' => 82],
    ['name' => 'Land Mecklenburg-Vorpommern', 'country_id' => 82],
    ['name' => 'Land Nordrhein-Westfalen', 'country_id' => 82],
    ['name' => 'Land Rheinland-Pfalz', 'country_id' => 82],
    ['name' => 'Land Sachsen', 'country_id' => 82],
    ['name' => 'Land Sachsen-Anhalt', 'country_id' => 82],
    ['name' => 'Land Thuringen', 'country_id' => 82],
    ['name' => 'Lower Saxony', 'country_id' => 82],
    ['name' => 'Mecklenburg-Vorpommern', 'country_id' => 82],
    ['name' => 'Mulfingen', 'country_id' => 82],
    ['name' => 'Munich', 'country_id' => 82],
    ['name' => 'Neubeuern', 'country_id' => 82],
    ['name' => 'Niedersachsen', 'country_id' => 82],
    ['name' => 'Noord-Holland', 'country_id' => 82],
    ['name' => 'Nordrhein-Westfalen', 'country_id' => 82],
    ['name' => 'North Rhine-Westphalia', 'country_id' => 82],
    ['name' => 'Osterode', 'country_id' => 82],
    ['name' => 'Rheinland-Pfalz', 'country_id' => 82],
    ['name' => 'Rhineland-Palatinate', 'country_id' => 82],
    ['name' => 'Saarland', 'country_id' => 82],
    ['name' => 'Sachsen', 'country_id' => 82],
    ['name' => 'Sachsen-Anhalt', 'country_id' => 82],
    ['name' => 'Saxony', 'country_id' => 82],
    ['name' => 'Schleswig-Holstein', 'country_id' => 82],
    ['name' => 'Thuringia', 'country_id' => 82],
    ['name' => 'Webling', 'country_id' => 82],
    ['name' => 'Weinstrabe', 'country_id' => 82],
    ['name' => 'schlobborn', 'country_id' => 82],
];