<?php return [
    ['name' => 'Acharnes', 'country_id' => 85],
    ['name' => 'Ahaia', 'country_id' => 85],
    ['name' => 'Aitolia kai Akarnania', 'country_id' => 85],
    ['name' => 'Argolis', 'country_id' => 85],
    ['name' => 'Arkadia', 'country_id' => 85],
    ['name' => 'Arta', 'country_id' => 85],
    ['name' => 'Attica', 'country_id' => 85],
    ['name' => 'Attiki', 'country_id' => 85],
    ['name' => 'Ayion Oros', 'country_id' => 85],
    ['name' => 'Crete', 'country_id' => 85],
    ['name' => 'Dodekanisos', 'country_id' => 85],
    ['name' => 'Drama', 'country_id' => 85],
    ['name' => 'Evia', 'country_id' => 85],
    ['name' => 'Evritania', 'country_id' => 85],
    ['name' => 'Evros', 'country_id' => 85],
    ['name' => 'Evvoia', 'country_id' => 85],
    ['name' => 'Florina', 'country_id' => 85],
    ['name' => 'Fokis', 'country_id' => 85],
    ['name' => 'Fthiotis', 'country_id' => 85],
    ['name' => 'Grevena', 'country_id' => 85],
    ['name' => 'Halandri', 'country_id' => 85],
    ['name' => 'Halkidiki', 'country_id' => 85],
    ['name' => 'Hania', 'country_id' => 85],
    ['name' => 'Heraklion', 'country_id' => 85],
    ['name' => 'Hios', 'country_id' => 85],
    ['name' => 'Ilia', 'country_id' => 85],
    ['name' => 'Imathia', 'country_id' => 85],
    ['name' => 'Ioannina', 'country_id' => 85],
    ['name' => 'Iraklion', 'country_id' => 85],
    ['name' => 'Karditsa', 'country_id' => 85],
    ['name' => 'Kastoria', 'country_id' => 85],
    ['name' => 'Kavala', 'country_id' => 85],
    ['name' => 'Kefallinia', 'country_id' => 85],
    ['name' => 'Kerkira', 'country_id' => 85],
    ['name' => 'Kiklades', 'country_id' => 85],
    ['name' => 'Kilkis', 'country_id' => 85],
    ['name' => 'Korinthia', 'country_id' => 85],
    ['name' => 'Kozani', 'country_id' => 85],
    ['name' => 'Lakonia', 'country_id' => 85],
    ['name' => 'Larisa', 'country_id' => 85],
    ['name' => 'Lasithi', 'country_id' => 85],
    ['name' => 'Lesvos', 'country_id' => 85],
    ['name' => 'Levkas', 'country_id' => 85],
    ['name' => 'Magnisia', 'country_id' => 85],
    ['name' => 'Messinia', 'country_id' => 85],
    ['name' => 'Nomos Attikis', 'country_id' => 85],
    ['name' => 'Nomos Zakynthou', 'country_id' => 85],
    ['name' => 'Pella', 'country_id' => 85],
    ['name' => 'Pieria', 'country_id' => 85],
    ['name' => 'Piraios', 'country_id' => 85],
    ['name' => 'Preveza', 'country_id' => 85],
    ['name' => 'Rethimni', 'country_id' => 85],
    ['name' => 'Rodopi', 'country_id' => 85],
    ['name' => 'Samos', 'country_id' => 85],
    ['name' => 'Serrai', 'country_id' => 85],
    ['name' => 'Thesprotia', 'country_id' => 85],
    ['name' => 'Thessaloniki', 'country_id' => 85],
    ['name' => 'Trikala', 'country_id' => 85],
    ['name' => 'Voiotia', 'country_id' => 85],
    ['name' => 'West Greece', 'country_id' => 85],
    ['name' => 'Xanthi', 'country_id' => 85],
    ['name' => 'Zakinthos', 'country_id' => 85],
];