<?php return [
    ['name' => 'Aasiaat', 'country_id' => 86],
    ['name' => 'Ammassalik', 'country_id' => 86],
    ['name' => 'Illoqqortoormiut', 'country_id' => 86],
    ['name' => 'Ilulissat', 'country_id' => 86],
    ['name' => 'Ivittuut', 'country_id' => 86],
    ['name' => 'Kangaatsiaq', 'country_id' => 86],
    ['name' => 'Maniitsoq', 'country_id' => 86],
    ['name' => 'Nanortalik', 'country_id' => 86],
    ['name' => 'Narsaq', 'country_id' => 86],
    ['name' => 'Nuuk', 'country_id' => 86],
    ['name' => 'Paamiut', 'country_id' => 86],
    ['name' => 'Qaanaaq', 'country_id' => 86],
    ['name' => 'Qaqortoq', 'country_id' => 86],
    ['name' => 'Qasigiannguit', 'country_id' => 86],
    ['name' => 'Qeqertarsuaq', 'country_id' => 86],
    ['name' => 'Sisimiut', 'country_id' => 86],
    ['name' => 'Udenfor kommunal inddeling', 'country_id' => 86],
    ['name' => 'Upernavik', 'country_id' => 86],
    ['name' => 'Uummannaq', 'country_id' => 86],
];