<?php return [
    ['name' => 'Agana Heights', 'country_id' => 89],
    ['name' => 'Agat', 'country_id' => 89],
    ['name' => 'Barrigada', 'country_id' => 89],
    ['name' => 'Chalan-Pago-Ordot', 'country_id' => 89],
    ['name' => 'Dededo', 'country_id' => 89],
    ['name' => 'Hagatna', 'country_id' => 89],
    ['name' => 'Inarajan', 'country_id' => 89],
    ['name' => 'Mangilao', 'country_id' => 89],
    ['name' => 'Merizo', 'country_id' => 89],
    ['name' => 'Mongmong-Toto-Maite', 'country_id' => 89],
    ['name' => 'Santa Rita', 'country_id' => 89],
    ['name' => 'Sinajana', 'country_id' => 89],
    ['name' => 'Talofofo', 'country_id' => 89],
    ['name' => 'Tamuning', 'country_id' => 89],
    ['name' => 'Yigo', 'country_id' => 89],
    ['name' => 'Yona', 'country_id' => 89],
];