<?php return [
    ['name' => 'Alta Verapaz', 'country_id' => 90],
    ['name' => 'Baja Verapaz', 'country_id' => 90],
    ['name' => 'Chimaltenango', 'country_id' => 90],
    ['name' => 'Chiquimula', 'country_id' => 90],
    ['name' => 'El Progreso', 'country_id' => 90],
    ['name' => 'Escuintla', 'country_id' => 90],
    ['name' => 'Guatemala', 'country_id' => 90],
    ['name' => 'Huehuetenango', 'country_id' => 90],
    ['name' => 'Izabal', 'country_id' => 90],
    ['name' => 'Jalapa', 'country_id' => 90],
    ['name' => 'Jutiapa', 'country_id' => 90],
    ['name' => 'Peten', 'country_id' => 90],
    ['name' => 'Quezaltenango', 'country_id' => 90],
    ['name' => 'Quiche', 'country_id' => 90],
    ['name' => 'Retalhuleu', 'country_id' => 90],
    ['name' => 'Sacatepequez', 'country_id' => 90],
    ['name' => 'San Marcos', 'country_id' => 90],
    ['name' => 'Santa Rosa', 'country_id' => 90],
    ['name' => 'Solola', 'country_id' => 90],
    ['name' => 'Suchitepequez', 'country_id' => 90],
    ['name' => 'Totonicapan', 'country_id' => 90],
    ['name' => 'Zacapa', 'country_id' => 90],
];