<?php return [
    ['name' => 'Atlantida', 'country_id' => 97],
    ['name' => 'Choluteca', 'country_id' => 97],
    ['name' => 'Colon', 'country_id' => 97],
    ['name' => 'Comayagua', 'country_id' => 97],
    ['name' => 'Copan', 'country_id' => 97],
    ['name' => 'Cortes', 'country_id' => 97],
    ['name' => 'Distrito Central', 'country_id' => 97],
    ['name' => 'El Paraiso', 'country_id' => 97],
    ['name' => 'Francisco Morazan', 'country_id' => 97],
    ['name' => 'Gracias a Dios', 'country_id' => 97],
    ['name' => 'Intibuca', 'country_id' => 97],
    ['name' => 'Islas de la Bahia', 'country_id' => 97],
    ['name' => 'La Paz', 'country_id' => 97],
    ['name' => 'Lempira', 'country_id' => 97],
    ['name' => 'Ocotepeque', 'country_id' => 97],
    ['name' => 'Olancho', 'country_id' => 97],
    ['name' => 'Santa Barbara', 'country_id' => 97],
    ['name' => 'Valle', 'country_id' => 97],
    ['name' => 'Yoro', 'country_id' => 97],
];