<?php return [
    ['name' => 'Bacs-Kiskun', 'country_id' => 99],
    ['name' => 'Baranya', 'country_id' => 99],
    ['name' => 'Bekes', 'country_id' => 99],
    ['name' => 'Borsod-Abauj-Zemplen', 'country_id' => 99],
    ['name' => 'Budapest', 'country_id' => 99],
    ['name' => 'Csongrad', 'country_id' => 99],
    ['name' => 'Fejer', 'country_id' => 99],
    ['name' => 'Gyor-Moson-Sopron', 'country_id' => 99],
    ['name' => 'Hajdu-Bihar', 'country_id' => 99],
    ['name' => 'Heves', 'country_id' => 99],
    ['name' => 'Jasz-Nagykun-Szolnok', 'country_id' => 99],
    ['name' => 'Komarom-Esztergom', 'country_id' => 99],
    ['name' => 'Nograd', 'country_id' => 99],
    ['name' => 'Pest', 'country_id' => 99],
    ['name' => 'Somogy', 'country_id' => 99],
    ['name' => 'Szabolcs-Szatmar-Bereg', 'country_id' => 99],
    ['name' => 'Tolna', 'country_id' => 99],
    ['name' => 'Vas', 'country_id' => 99],
    ['name' => 'Veszprem', 'country_id' => 99],
    ['name' => 'Zala', 'country_id' => 99],
];